### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by oleg0xff** [ermig1979/Simd#1]
I can't compile it because there are no file  SimdVersion.h. 
I have message "fatal error: Simd/SimdVersion.h: No such file or directory  #include "Simd/SimdVersion.h"

**Comment by ermig1979** [comment]
There are a generators of SimdVersion.h file (prj/cmd/GetVersion.cmd for Windows and prj/sh/GetVersion.sh for Linux). These generators are started automatically during build process (see files prj/vs11/Simd.vcxproj and prj/cmake/CMakeLists.txt).

**Comment by oleg0xff** [comment]
Now I generate it by using other directory and it will generate version file. (I do "cd prj/cmake" and "cmake ." and "make" after).
 But another issue appear - I have following output :
CMakeFiles/Test.dir/home/ryabov/Documents/Simd/src/Test/Test.cpp.o: In function `ExecuteAutoTest(Options const&)':
Test.cpp:(.text+0x7492): undefined reference to `Test::SvmSumLinearAutoTest()'
CMakeFiles/Test.dir/home/ryabov/Documents/Simd/src/Test/Test.cpp.o: In function `ExecuteDataTest(Options const&)':
Test.cpp:(.text+0x123be): undefined reference to `Test::SvmSumLinearDataTest(bool)'
/home/ryabov/Documents/Simd/bin/Release/libSimd.so: undefined reference to `Simd::Avx::SvmSumLinear(float const*, float const*, float const*, unsigned long, unsigned long, float*)'
/home/ryabov/Documents/Simd/bin/Release/libSimd.so: undefined reference to `Simd::Base::SvmSumLinear(float const*, float const*, float const*, unsigned long, unsigned long, float*)'
/home/ryabov/Documents/Simd/bin/Release/libSimd.so: undefined reference to `Simd::Sse::SvmSumLinear(float const*, float const*, float const*, unsigned long, unsigned long, float*)'
collect2: error: ld returned 1 exit status

What should I do to compile it?

**Comment by ermig1979** [comment]
I'm sorry, but I forgot to add TestSvm.cpp file. I already commited it. You must update your local repository. Thank you for bug report.

**Comment by oleg0xff** [comment]
It works fine, thanks. It looks like your app faster than opencv.
