### ISSUE TITLE
How to show detection results using OPENCV

### ISSUE THREAD

**Issue by lsy17096535** [ermig1979/Simd#10]
Hi, 
Thanks for your project. I use example code to detect face, the code save result on disk. I don't know how to input image form camera and show result on screen based on OPENCV. Could you tell me how to do that. Thank you.

**Comment by lsy17096535** [comment]
i find the example code in header files, thank you.

**Comment by ermig1979** [comment]
Nevertheless I have added an [example](https://github.com/ermig1979/Simd/blob/master/src/Use/UseFaceDetection.cpp).

**Comment by lsy17096535** [comment]
Do you have any plan to write a tracking algorithm with SIMD? With which we can get faster object tracking results. 
Sincerely, Siyuan.

**Comment by ermig1979** [comment]
I have started to write [Motion Detector](https://github.com/ermig1979/Simd/blob/master/src/Simd/SimdMotion.hpp) but the work still is too far from the end.

**Comment by lsy17096535** [comment]
@ermig1979 Thank you .
