### ISSUE TITLE
Error building v4.3.79

### ISSUE THREAD

**Issue by mikeversteeg** [ermig1979/Simd#101]
I'm unable to build the latest release, getting: 

```
Error	MSB3073	The command ""E:\My Documents\SimdLib\prj\vs2017w\..\cmd\GetVersion.cmd" "E:\My Documents\SimdLib\prj\vs2017w\..\.."
:VCEnd" exited with code 1.

```
I don't use VS so may be doing something wrong, but never had an issue with older versions. Using VS2017. Thanks.

**Comment by ermig1979** [comment]
It seems that I fixed the error. Could you check is it true?

**Comment by mikeversteeg** [comment]
Confirmed, thanks!
