### ISSUE TITLE
Does it support HOG+SVM for object detection?

### ISSUE THREAD

**Issue by zanazakaryaie** [ermig1979/Simd#103]
Hi

I want to train a HOG+SVM detector in OpenCV and then use your library for acceleration. Does it support both HOG and SVM?

**Comment by ermig1979** [comment]
Simd does not support OpenCV HOG models.

**Comment by zanazakaryaie** [comment]
Sure. DNNs are generally better than classical algorithms that work based on hand-crafted features. But it all depends on the processor power. I'm using a low-end ARM processor. Even the fastest deep object detectors like Yolo or SSD are too slow for my application. I'm looking for a lower-accuracy but much higher performance.

**Comment by ermig1979** [comment]
Lately I develop [a project](https://github.com/ermig1979/Synet) to fast inference of previously trained neural models. It is something like Inference Engine but it  also supports ARM CPU. May be it will be useful for you.  For our purposes (faces and licence plates detection) on mobile CPU its performance is good enough.

**Comment by zanazakaryaie** [comment]
Hi again. Thank you very much. I didn't know that. I will test it as soon as possible. Thanks again :)
