### ISSUE TITLE
Is it possible to detect eye after finding the face?

### ISSUE THREAD

**Issue by Arunvist** [ermig1979/Simd#104]
With this simd source after finding the face detecting eye is possible?

**Comment by ermig1979** [comment]
Yes, it is possible. You can also use Simd::Detector, but with other cascade which detect eyes (for example you can use [this](https://github.com/opencv/opencv/blob/master/data/haarcascades/haarcascade_eye.xml)).

But using of Haar Cascades now is not the best idea. Lately I develop a [project](https://github.com/ermig1979/Synet) to fast inference of previously trained neural models. It is something like Inference Engine but it also supports ARM CPU. May be it will be useful for you. Test examples contain models trained for face detection and face landmarks detection (some of landmarks are correspond to eyes).
