### ISSUE TITLE
How can do binarization image like cv::threshold, use "OTSU" auto threshold parameters!

### ISSUE THREAD

**Issue by sheiling** [ermig1979/Simd#105]
Hello, my some code will use cv::threshold, and use "OTSU"、"BINARY" parameters. So I will get some piece of code from "simd", what can I do it proper? thanks for help me!

**Comment by ermig1979** [comment]
I could add function which calculates Otsu threshold. Other functions (histogram calculation and image binarization are exist already in Simd).

**Comment by sheiling** [comment]
good ! I write a naive code by myself! and use histogram and binarization functions from "simd", could I submit it to "simd"!

**Comment by ermig1979** [comment]
Yes of course.

**Comment by ermig1979** [comment]
[https://stackoverflow.com/questions/33693423/otsu-thresholding](url)

**Comment by axllou** [comment]
May I ask is there already having implement of otsu thresholding in simd? Thanks.

**Comment by ermig1979** [comment]
I'm so sorry but I could not find time to do this issue. I will do it when I have free time.

**Comment by ermig1979** [comment]
Hi! Its seems unbelievable but I added function to calculate Otsu threshold. :)
