### ISSUE TITLE
Object Measurement

### ISSUE THREAD

**Issue by syberarall** [ermig1979/Simd#109]
The SIMD library is great, but I'm not shure how I do some object measurement (e.g. finding the centre point of an object). Maybe you could list me just the functions to use: This would be very helpful.

**Comment by syberarall** [comment]
Dear Ihar,

 

thanks for your response. I tried it, but have still some troubles.

I have following picture:

 

__pSyncSrcBuffer



 

#define SIZE_X                                500

#define SIZE_Y                                400

#define STRIDE_GRAY8                               SIZE_X

#define STRIDE_INT16                  SIZE_X*2

 

typedef Simd::View<Simd::Allocator> View;

View ViewSrcGray8(SIZE_X, SIZE_Y, STRIDE_GRAY8, View::Gray8, __pSyncSrcBuffer);

View ViewDstInt16(SIZE_X, SIZE_Y, STRIDE_INT16, View::Int16, __pSyncDstBuffer);

View ViewDstGray8(SIZE_X, SIZE_Y, STRIDE_GRAY8, View::Gray8, __pMaskBuffer);

 

Simd::ContourMetrics(ViewSrcGray8, ViewDstInt16);

Simd::Int16ToGray(ViewDstInt16, ViewDstGray8);

 

uint8_t Index = 255; //Color of pixel

uint64_t area = 0;

uint64_t x    = 0;

uint64_t y    = 0;

uint64_t xx   = 0;

uint64_t xy   = 0;

uint64_t yy   = 0;

 

Simd::GetMoments(ViewDstGray8, Index, area, x, y, xx, xy, yy);

 

uint64_t cx = (xx / x);

uint64_t cy = (yy / y);

 

__pMaskBuffer



 

The resulting values are



 

The rectangle should match the centre of the ring, but doesn’t. What goes wrong ?

Thanks for your help in advance.

 

Best regards,

 

Jürgen Rall

 



 

 

 

Von: Ihar Yermalayeu [mailto:notifications@github.com] 
Gesendet: Donnerstag, 24. Oktober 2019 08:38
An: ermig1979/Simd
Cc: syberarall; Author
Betreff: Re: [ermig1979/Simd] Object Measurement (#109)

 

Simd has next function:
http://ermig1979.github.io/Simd/help/group__other__statistic.html#ga826cc6d930c49626110ca8e750c4338f

Is it useful for your case?

**Comment by syberarall** [comment]
Dear Ihar,
thanks for your advice. Using

typedef Simd::View<Simd::Allocator> View;
View ViewSrcGray8(SIZE_X, SIZE_Y, STRIDE_GRAY8, View::Gray8, __pSyncSrcBuffer);
 Simd::GetMoments(ViewSrcGray8, Index, area,	x, y,	xx, xy, yy)

works, but Simd::Base::GetMoments(__pSyncDstBuffer, STRIDE_GRAY8, SIZE_X,SIZE_Y,0, &area, &x,&y,&xx,&xy,&yy)

not. Why ?

**Comment by ermig1979** [comment]
Check: if __pSyncDstBuffer == NULL then View creates new image.

**Comment by syberarall** [comment]
__pSyncDstBuffer = __pSyncSrcBuffer and is valid and Simd::Base::GetMoments get results, but different one to Simd::GetMoments.

Simd::GetMoments -> area = 5812, x = 726274, y = 1756969, result is OK
Simd::Base::GetMoments -> area = 193561, x = 49009015, y = 38142691, result is wrong

**Comment by syberarall** [comment]
I did some debugging - has it to do with alignment stuff ?

**Comment by ermig1979** [comment]
May be, I can't reproduce this bug.

**Comment by ermig1979** [comment]
A added more universal function to collect object moments: [GetObjectMoments](http://ermig1979.github.io/Simd/help/group__other__statistic.html#ga38eb71fc90753224e9309eb4681c1052).

**Comment by syberarall** [comment]
Dear Ihar,

 

I want to do face detection with SIMD Version 4381 and took some sample from the web.

My code looks like:

 

PGVSP_IMAGE_DATA_LEADER pLeader = (PGVSP_IMAGE_DATA_LEADER)pBuffer;

PUCHAR pData = (PUCHAR)&pBuffer[sizeof(GVSP_IMAGE_DATA_LEADER)];

ULONG SizeX = 0;

ULONG SizeY = 0;

ULONG PixelFormat = 0;

 

//Get image leader elements

ETH_GET_BIGENDIAN_ULONG(pLeader->size_x, &SizeX);

ETH_GET_BIGENDIAN_ULONG(pLeader->size_y, &SizeY);

ETH_GET_BIGENDIAN_ULONG(pLeader->pixel_format, &PixelFormat);

 

//Process image

if ((SizeX) && (SizeY))

{

         ULONG StrideGray8 = SizeX;

         ULONG StrideInt16 = SizeX * 2;

 

         {

                 typedef Simd::Detection<Simd::Allocator> DetectionType;

                 DetectionType MyDetection;

                 DetectionType::Objects MyObjects;

                 DetectionType::View image(SizeX, SizeY, StrideGray8, DetectionType::View::Gray8, pData);

MyDetection.Load("D:\Sybera\Sha64\Cores\GevCore64\Utilities\Simd4381\data\cascade\haar_face_0.xml");

                 if (__bDetectInitDone == FALSE)

                 {

                          MyDetection.Init(image.Size(), 1.2, image.Size() / 20);

                          __bDetectInitDone = TRUE;

                 }

 

                 MyDetection.Detect(image, MyObjects);

         }

}

 

On compilation I Get an error at MyDetection.Detect(image, MyObjects) out of the library SIMDDETECTION.HPP at line 687:

'(': illegal token on right side of '::'

Do you have any idea ?

Best regards,

 

Jürgen Rall

**Comment by ermig1979** [comment]
Hello!
There are no '(' or '::' at line 687 in the file SimdDetection.hpp !
And there are no changes in code of this file this year.

**Comment by syberarall** [comment]
Dear Ihar,

 

here is what I mean when I try to compile my code:

 



 

 

regards,

 

Jürgen Rall

 



 

 

 

 

Von: Ihar Yermalayeu [mailto:notifications@github.com] 
Gesendet: Mittwoch, 15. Juli 2020 15:09
An: ermig1979/Simd
Cc: syberarall; Author
Betreff: Re: [ermig1979/Simd] Object Measurement (#109)

 

Hello!
There are no '(' or '::' at line 687 in the file SimdDetection.hpp !
And there are no changes in code of this file this year.

**Comment by ermig1979** [comment]
Could you comment at one place (in the open issue)?
