### ISSUE TITLE
Compilation error for SimdDetection

### ISSUE THREAD

**Issue by pallegd** [ermig1979/Simd#11]
Compiling code using SimdDetection raises the following two errors for SimdDetection.hpp:

../simd/src/Simd/SimdDetection.hpp:178:41: error: ‘INT_MAX’ was not declared in this scope
             const Size & sizeMax = Size(INT_MAX, INT_MAX), const View & roi = View(), ptrdiff_t threadNumber = -1)
                                         ^~~~~~~
../simd/src/Simd/SimdDetection.hpp:178:50: error: ‘INT_MAX’ was not declared in this scope
             const Size & sizeMax = Size(INT_MAX, INT_MAX), const View & roi = View(), ptrdiff_t threadNumber = -1)
                                                  ^~~~~~~

This can be solved by 
#include <limits.h>

in SimdDetection.hpp

**Comment by ermig1979** [comment]
Thank you. I will add this fix.
