### ISSUE TITLE
CNN

### ISSUE THREAD

**Issue by mikeversteeg** [ermig1979/Simd#112]
I don't know what your developments are with CNN, but can your library be used to create an AI? I'm interested in automation of camera control for sports productions and I feel this is a job for an AI.

**Comment by ermig1979** [comment]
I develop a project to inference of trained CNN on CPU: 
[https://github.com/ermig1979/Synet](https://github.com/ermig1979/Synet).
This project uses Simd as a backend to accelerate inference of CNN.

**Comment by mikeversteeg** [comment]
Is it purely theoretical research, or are you working on or aiming for a real life application? I'm obviously glad you chose to take the CPU route, but why not use the GPU? The challenge?

**Comment by ermig1979** [comment]
I develop video analytics. It is a cloud system and it runs on server CPUs. We use small CNNs and using of GPU does not give obvious advantage. The best performance is achieved if we process each video stream in a separate thread in a single-thread mode. It is main cause to develop Synet and Simd. 
Now I am starting project to port analytics to GPU. It will be a long process bеcause we need to change whole architecture of our project.

**Comment by mikeversteeg** [comment]
Much the same reasons why I prefer the CPU :).

Video analytics? Interesting! Is it a commercial product or a hobby? I'd like to read more about it, it may even be interesting for some of my clients.

**Comment by ermig1979** [comment]
We are develop [Kipod ](https://kipod.com/).
