### ISSUE TITLE
quick fix in documentation

### ISSUE THREAD

**Issue by m-parchami** [ermig1979/Simd#121]
Hey there.
The documentation of `SimdDetection.hpp` may need a quick fix.
The `LoadStringXml` function, takes a string(which would be our XML). However, on the documentation which is right above the signature, we have:
> \param [in] xml - a path to cascade.

which is probably a mistake while copying and pasting from the normal `Load` function.

**Comment by ermig1979** [comment]
Thank you for bug report! The bug has been fixed.
