### ISSUE TITLE
Win7X64 + VS2017 + simd/prj/vs2017w, Compile error

### ISSUE THREAD

**Issue by dbyoung720** [ermig1979/Simd#123]
Win7X64 + VS2017 + simd/prj/vs2017w, Compile error

Error C3861 '_mm256_extract_epi64': identifier not found		e:\source\sse\simd\src\simd\simdextract.h	182

**Comment by ermig1979** [comment]
Hello! Thank you for bug report.
I have checked compilation on Visual Studio 2017 and it works fine.
The troubles may be caused the fact then I use newer version 15.7 of Visual Studio (_MSC_VER = 1914) unlike  of you. If you tell me your compiler version (_MSC_VER ) it will help to reproduce error and then fix it.

**Comment by dbyoung720** [comment]
Version 15.9.21

**Comment by ermig1979** [comment]
I have reproduced this bug (at 32-bit mode) and fixed.
