### ISSUE TITLE
Release benchmarks for common CNN networks.

### ISSUE THREAD

**Issue by Timen** [ermig1979/Simd#127]
I was wondering there is a list available somewhere showing benchmarks for common networks such as Resnet,mobilenet (v1/2/3), squeezene(x)t etc. ? 

The library looks impressive but being able to compare performance for common network backbones helps people choose for this library if it is faster compared to other available inference engines.

**Comment by ermig1979** [comment]
Now Simd::Neural is deprecated. I develop other project [Synet](https://github.com/ermig1979/Synet) concerned with inference of trained neural network. Synet has benchmarks to compare it with another frameworks. Simd Library has only low level functions to optimize CNN.

**Comment by Timen** [comment]
Are the benchmark results of Synet publicly available somewhere? I can't find any references to it on the project page.

**Comment by ermig1979** [comment]
There are no results in public domain. I performed private comparison with OpenVINO (single thread for every network inference), Synet is faster for 30-40%. I can publish some of these results.

**Comment by Timen** [comment]
That would be great! It would really help comparing Synet/SIMD to other options out there. Even better would be if you include a script to reproduce the benchmark results with the actual results so people can easily reproduce the results and possibly run their own benchmarks on their specific deployment hardware.

**Comment by ermig1979** [comment]
There is a script perf.sh in Synet to perform this benchmark.

**Comment by Timen** [comment]
Ok thanks! I'll have a look but nonetheless it may still be handy to have the benchmark results available publicly so one can look at them without having to build the project :)
