### ISSUE TITLE
Ошибка в коде к статье на Habr

### ISSUE THREAD

**Issue by GlebBrykin** [ermig1979/Simd#129]
Здравствуйте!
Хочу сообщить об ошибке в коде к Вашей статье https://m.habr.com/ru/post/448436/, а именно в базовой реализации свёртки. depthwise свёртка(с group > 1) вычисляется некорректно: значения есть только у первых каналов, последующие же каналы заполнены нулями.

**Comment by ermig1979** [comment]
Здравствуйте! В коде который в статье - я специально сильно сокращал, что бы он влез в формат статьи. Видимо перестарался. Ошибочный вариант в формате NCHW или NHWC?

**Comment by GlebBrykin** [comment]
В NCHW.

**Comment by GlebBrykin** [comment]
Обнаружил ещё одну ошибку в оптимизированном коде к той же статье. Формат NCHW. Обычная свёртка работает правильно, depthwise вылетает при попытке доступа в защищённую память(выход за границы массива если использовать указатели).

**Comment by ermig1979** [comment]
Спасибо за сообщение об ошибке. Исправил.

**Comment by GlebBrykin** [comment]
К сожалению, ошибка сохраняется.18.09.2020, 09:20, "Ihar Yermalayeu" <notifications@github.com>:
Спасибо за сообщение об ошибке. Исправил.

**Comment by GlebBrykin** [comment]
Я запускаю этот код в C#, т.к. это позволяет проще находить ошибки. Из изменений - только удаление модивикатора const в параметрах функций, всё остальное - как на Хабре. Код скопировал сразу после Вашего сообщения. Прикрепляю файл с полным кодом для воспроизведения ошибки. Хочу отметить, что обычная свёртка с разными разерами шага работает корректно.

**Comment by GlebBrykin** [comment]
https://yadi.sk/d/VBjs92hBaeZ3Vw18.09.2020, 09:46, "Брыкин Глеб" <glebbrykin@yandex.ru>:Я запускаю этот код в C#, т.к. это позволяет проще находить ошибки. Из изменений - только удаление модивикатора const в параметрах функций, всё остальное - как на Хабре. Код скопировал сразу после Вашего сообщения. Прикрепляю файл с полным кодом для воспроизведения ошибки. Хочу отметить, что обычная свёртка с разными разерами шага работает корректно.

**Comment by ermig1979** [comment]
По ваше ссылке говорит, что ничего не найдено.

**Comment by ermig1979** [comment]
Впрочем еще одну ошибку я нашел.

**Comment by GlebBrykin** [comment]
Да, слепилась ссылка с временем отправки письма. https://yadi.sk/d/VBjs92hBaeZ3Vw - правильная ссылка.

**Comment by GlebBrykin** [comment]
Проверил ещё и базовую реализацию. Там проблема сохранилась - первый канал заполняется данными, остальные - нет. https://yadi.sk/d/U-Av6u-O4eu9LQ Вот файл.

**Comment by GlebBrykin** [comment]
Итак, проблемы сохраняются в обоих кодах - что оптимизированном, что в базовом. Сейчас смотрю на оптимизированную версию и вижу такую строку:
```
int M = dstC / group;
```
Довольно странно, учитывая то, что group связан только с srcC и глубиной ядра, но выходные каналы с группами никак не связаны!!! Количество ядер свёртки и только оно определяет выходную глубину. Это первое.
Второе - это чехарда с group в этой строке:
```
gemm_nn(M, N, K, 1, weight + M * K * g, K, 0, buf + N * K * g, N, dst + M * N * g, N);
```

**Comment by GlebBrykin** [comment]
Ошибки в быстрой реализации исправлены. Прошу прощения, не заметил у себя ошибку в тестовом коде.

**Comment by GlebBrykin** [comment]
И всё же ошибка есть... На маленьких размерах данных быстрый алгоритм(через матричное умножение) работает корректно для всех проверенных условий. Результаты работы алгоритма совпадают с результатами в PyTorch. Однако стоит увеличить объемы данных до адекватных размеров, как появляются несоответствия с PyTorch. Я интегрировал Ваш код в своё работающее приложение для стилизации изображений и получил некорректный результат. Если необходимо, могу предоставить все исходные коды.

**Comment by GlebBrykin** [comment]
Под маленькими размерами данных понимается размер входного массива 1 * 3 * 5 * 5 и 3 * 3 * 3 * 3 для весов свёртки. Под реальными размерами - 1 * 128 * 256 * 256 для входного массива и 128 * 128 * 3 * 3 для массива весов.

**Comment by ermig1979** [comment]
А на сколько некорректный?

**Comment by GlebBrykin** [comment]
Совсем некорректный. Вот, для примера, результат:
#
![IMG_20200922_095155](https://user-images.githubusercontent.com/36363358/93851705-49786e00-fcb9-11ea-9fc5-af6f96f6fc8f.jpg)
Это я получаю вместо нормального изображения. Вот здесь: https://github.com/ColorfulSoft/StyleTransfer-Colorization-SuperResolution/tree/master/Style%20Transfer/2017.%20Arbitrary%20Style%20Transfer%20in%20Real-time%20with%20Adaptive%20Instance%20Normalization можно посмотреть на то, что получается с обычной свёрткой. Странно, что на небольших объёмах данных Ваш код работает правильно, а на больших - нет. Я пока даже не могу предположить, в чём может быть проблема. Ошибок выхода за границы массива не возникало. Причём одинаковая картина и с Вашей версией базовой реализации свёрки и с быстрой.

**Comment by GlebBrykin** [comment]
Может быть, проблема в .NET, но чтобы это проверить, необходимо запустить Ваш код на C++.

**Comment by ermig1979** [comment]
Хорошо. Как будет свободное время напишу тесты для С++ версии.

**Comment by GlebBrykin** [comment]
Ошибка в .NET крайне маловероятна. Сейчас проверил свою реализацию свёртки с указателями и никаких проблем не наблюдаю.

**Comment by ermig1979** [comment]
А у вас какой размер внешнего буфера? Требуется как минимум srcC*kernelY*kernelX*dstH*dstW.

**Comment by GlebBrykin** [comment]
Такой и есть. Вчера ещё несколько тестов провёл, полное совпадение с PyTorch во всех проверенных случаях(разница отдельных значений менее 0.001), но стилизация пока что не работает. Буду дальше искать решение.

**Comment by GlebBrykin** [comment]
Переполнения int32 не было, более того, быть не могло, т.к. в C# создать массив длиной больше максимального значения int простым способом невозможно. Попытка сделать это вызывает исключение. А выделение памяти я провожу как раз через создание массивов и последующее получение указателей на них. Да и проверку на переполнение я включал. Переполнений не было.

**Comment by GlebBrykin** [comment]
Ещё хотел бы спросить про обратное распространение ошибки через быструю свёртку. Я прикинул и получил такие формулы(в терминологии Вашей статьи):

dA = C * B^t
dB = A^t * C
При этом dB потребует преобразование, обратное im2col.

Я прав?

**Comment by GlebBrykin** [comment]
> А у вас какой размер внешнего буфера? Требуется как минимум `srcC*kernelY*kernelX*dstH*dstW`.
> Просто, если на малых размерах работает, а на больших нет, то только две возможные причины: переполнение переменных (32 bit int вроде не переполняется) и переполнение буфера.

В таком случае в статье есть ещё одна ошибка: 
![2lcmlpitdsgjyztxnyylyqi62jo](https://user-images.githubusercontent.com/36363358/94059172-bb9ca000-fdea-11ea-83f2-289272734c60.png)
Ведь исходя из изображения, количество элементов буффера делится на group, однако этого количества недостаточно: в программе возникает ошибка.

Ещё одна ошибка непосредственно в коде:
В void convolution:
```
im2row(src, srcC, srcH, srcW, kernelY, kernelX, dilationY, dilationY,
      strideY, strideX, padY, padX, padH, padW, group, buf);
```
Два dilationY вместо dilationY, dilationX.

**Comment by ermig1979** [comment]
В буфере не надо делить количество элементов на группы. Функции `im2col` и `im2row` преобразуют входное изображение целиком.
P.S. Исправил ошибку с `dilationX`.
