### ISSUE TITLE
nv12 convert to rgb

### ISSUE THREAD

**Issue by w136111526** [ermig1979/Simd#133]
Hello, I would like to convert the NV12 image to-bit rgb image, there is no function available

**Comment by ermig1979** [comment]
See function Convert in file [SimdFrame.hpp](https://github.com/ermig1979/Simd/blob/master/src/Simd/SimdFrame.hpp), line 712:

            case Frame<A>::Bgr24:
            {
                View<A> u(src.Size(), View<A>::Gray8), v(src.Size(), View<A>::Gray8);
                DeinterleaveUv(src.planes[1], u, v);
                Yuv420pToBgr(src.planes[0], u, v, dst.planes[0]);
                break;
            }
