### ISSUE TITLE
Test BgrToRgb crashed.

### ISSUE THREAD

**Issue by teor292** [ermig1979/Simd#142]
Hi. I clone last Simd library and found that test crash after execution of BgrToRgb function.
I think mistake is here:

FuncN call BgrToRgb function like this:
` func(src.data, src.stride, src.width, src.height, dst.data, dst.stride);`
But BgrToRgb has another header:

`void BgrToRgb(const uint8_t * bgr, size_t width, size_t height, size_t bgrStride, uint8_t * rgb, size_t rgbStride)`

So, I think it is nesseccary to change call to

` func(src.data, src.width, src.height, src.stride, dst.data, dst.stride);`

Thanks.

**Comment by ermig1979** [comment]
It is my blame: I changed API of function BgrToRgb and forgot to update test. I fixed it. Thank you for bug report!
