### ISSUE TITLE
Assert in SynetMergedConvolution32fCdc::Set

### ISSUE THREAD

**Issue by teor292** [ermig1979/Simd#143]
Hi again. When run test there is another bug in 
`SynetMergedConvolution32fCdc::Set`
`p.conv[i].activation` is `SimdConvolutionActivationMish` but there is no `case` for it in this function. 
Here is screenshot:

[https://drive.google.com/file/d/1p0P25P9Fl4gr8jphBhTJu9bONFqQJyZP/view?usp=sharing](https://drive.google.com/file/d/1p0P25P9Fl4gr8jphBhTJu9bONFqQJyZP/view?usp=sharing)

**Comment by ermig1979** [comment]
Thank you for bug report. I have fixed it. 
This bug did not affect to real code in release mode.
