### ISSUE TITLE
Issue in SynetConvolution32fNhwcDirect::OldReorderWeight

### ISSUE THREAD

**Issue by teor292** [ermig1979/Simd#145]
Hi. I use Simd with Synet to test perfomance of some neural networks. It works fine on Windows (x64) and Linux (x64). But on ARMv7 compiled with gcc 6.3.0 it freezes.

I don't know the reason, but here what I found.

Here is start piece of code of SynetConvolution32fNhwcDirect::OldReorderWeight:
```
const ConvParam32f& p = _param; 
const AlgParam& a = _old.alg;
for (size_t da = 0; da < p.dstC; da += a.macroD)
```
Parameters of AlgParam on x64 are as follows:
```
F  8
microD	16
macroH	10
macroC	3
macroD	16
```
Others contain some trash as I think.

But on ARMv7 this values are as follows:

```
F 4
microD	8
macroH	10
macroC	3
macroD	0 (!)
```

So `for (size_t da = 0; da < p.dstC; da += a.macroD)` go to infinite loop (p.dstC == 10).
I am hope for your help.

**Comment by ermig1979** [comment]
It signilizes to wrong algorithm of L3 cache size getting on ARMv7. Unfortunately I can't get access to this platform now to reproduce bug. I can try to fix this issue but can't check it.

**Comment by teor292** [comment]
Ok, but I can check it :) 
If you need some kind of debugging information, I can try to provide it.

**Comment by ermig1979** [comment]
Could you check bug fix?
[SimdBaseSynetConvolution32f.zip](https://github.com/ermig1979/Simd/files/6196142/SimdBaseSynetConvolution32f.zip)

**Comment by teor292** [comment]
Well, now the neural network is loading, but freezes during calculation. I'll try to find a moment.

**Comment by teor292** [comment]
Ok, I found it.

In file SimdGemm.h:

at line 371:

```
        void Run(size_t M, const T * A, size_t lda, const T * pB, T * C, size_t ldc)
        {
            assert(M <= _M);
            for (size_t j = 0; j < _N; j += _macroN)
```
_macroN == 0

**Comment by ermig1979** [comment]
The second iteration:
[SimdGemm.zip](https://github.com/ermig1979/Simd/files/6196787/SimdGemm.zip)

**Comment by teor292** [comment]
Everything works, thank you!

**Comment by ermig1979** [comment]
It's good news!
