### ISSUE TITLE
resize from (3328,1032) to (3752,1080) is slower than opencv4.5.1

### ISSUE THREAD

**Issue by zacario-li** [ermig1979/Simd#149]
Hi,
    cv::resize is much faster than simd::resize. Is there any problem?
    OS: Win10 Pro (1909)
    CPU: i7-10700
    RAM: 32G  
 |method|cost(s)|
 | :------: | :------: |
 |cv::resize|0.003689|
 |simd::resize|0.009789|

**Comment by ermig1979** [comment]
Hi!

I think that main reason of this behavior is that Simd::Resize works at single thread but cv::resize uses multithreading.

**Comment by zacario-li** [comment]
> Hi!
> 
> I think that main reason of this behavior is that Simd::Resize works at single thread but cv::resize uses multithreading.
> 
> P.S.
> OpenCV is developed to achieve maximal performance at work station and maximal uses multithreading to minimize function execution time for single user. I developed Simd to work in server environment: it works mainly in single thread and avoids internal algorithm multithreading in order to achieve maximal utilization of CPU resources at multithread using.

Thanks for your explanation.
