### ISSUE TITLE
Scale buffer pixel

### ISSUE THREAD

**Issue by AhmedX6** [ermig1979/Simd#15]
Hello,

I have a buffer of pixels (BGRA) of a 1920x1080 image. The length is 1920*1080*4.
I would like to scale this buffer to 1280x720.
How to do this using Simd library ? I don't find any sample or documentation.

Thank you !

**Comment by ermig1979** [comment]
You could use function [SimdResizeBilinear](http://ermig1979.github.io/Simd/help/group__resizing.html#ga1dd25f3a0d5736af1db87518b379f23f).
In your case:

    const uint8_t * src; // input buffer
    size_t srcWidth = 1920;
    size_t srcHeight = 1080;
    size_t srcStride = 1920*4; //in common case: srcBufferSize/srcHeight;
    uint8_t * dst; // output buffer
    size_t dstWidth = 1280;
    size_t dstHeight = 720;
    size_t dstStride = 1280*4; //in common case: dstBufferSize/dstHeight;
    size_t channelCount = 4;

    SimdResizeBilinear(src, srcWidth, srcHeight, srcStride, dst, dstWidth, dstHeight, dstStride, channelCount);

**Comment by AhmedX6** [comment]
Thank you for your answer.
I would like to test this ... But impossible to compile Simd Library with VS2017. 
I got this error on the build : 
```
Severity	Code	Description	Project	File	Line	Suppression State
...\Simd\prj\vs2015\\..\cmd\GetVersion.cmd
:VCEnd" exited with code 9009
```
Isn't it possible to have prebuilt static .lib for every architecture on release ?
I see many librarys included in NuGet Package. It is much more practical and it avoids full of worries.

Thanks again !

**Comment by ermig1979** [comment]
I would recommend to use for VS2017 corresponding project files which are placed in the directory :
...\Simd\prj\vs2017w\

..\Simd\prj\vs2015 contains VS2015 project files.

As to uploading of compiled static .lib for every release of Simd Library - I will think.

**Comment by AhmedX6** [comment]
Thanks. The build is successful with the project in \prj\vs2017w\
I compiled it as static as I prefer not having dll's.
For the include header files it's located on  Simd\src, isn't it ?
My project is a C++ project so I included "simdlib.hpp"
I'm getting an exception on this line after using the `SimdResizeBilinear` function on this line : 
`template <> SIMD_INLINE void Store<false>(__m256i * p, __m256i a)
        {
            _mm256_storeu_si256(p, a);
        }`

Here is my code : 
```
BYTE *Duplication::scaleBufferSimd(unsigned char * data)
{
	BYTE buffer;
	size_t srcWidth = GetSystemMetrics(SM_CXSCREEN); //1920
	size_t srcHeight = GetSystemMetrics(SM_CYSCREEN); //1080
	size_t srcStride = GetSystemMetrics(SM_CXSCREEN) * BPP4;  //1920 * 4

	size_t dstWidth = mWidthResolutionSelected; //1280
	size_t dstHeight = mHeightResolutionSelected; //720
	size_t dstStride = mWidthResolutionSelected * BPP4;  //1280 * 4
	size_t channelCount = BPP4;

	SimdResizeBilinear(data, srcWidth, srcHeight, srcStride, &buffer, dstWidth, dstHeight, dstStride, channelCount);
	return &buffer;
}
```
What did I do wrong ? Thank you very much

**Comment by ermig1979** [comment]
Of course wrong!
Parameter dst must point to output buffer of corresponding size: 

    BYTE *Duplication::scaleBufferSimd(unsigned char * data)
    {
	size_t srcWidth = GetSystemMetrics(SM_CXSCREEN); //1920
	size_t srcHeight = GetSystemMetrics(SM_CYSCREEN); //1080
	size_t srcStride = GetSystemMetrics(SM_CXSCREEN) * BPP4;  //1920 * 4

	size_t dstWidth = mWidthResolutionSelected; //1280
	size_t dstHeight = mHeightResolutionSelected; //720
	size_t dstStride = mWidthResolutionSelected * BPP4;  //1280 * 4
	size_t channelCount = BPP4;
	BYTE * buffer = SimdAllocate(dstStride*dstHeight, SimdAlignment());

	SimdResizeBilinear(data, srcWidth, srcHeight, srcStride, buffer, dstWidth, dstHeight, dstStride, channelCount);
	return buffer;
    }

And later (after using)  don't forget to delete output buffer with using of function SimdFree().

**Comment by AhmedX6** [comment]
Thank you very much !
Yes I did it and it works very well.
Many thanks !

**Comment by RoyiAvital** [comment]
By the way, do you have Gaussian Blur with arbitrary radius in the library?

**Comment by ermig1979** [comment]
There is no special function to perform Gaussian Blur with arbitrary radius in the library. But you can use function [SimdHogFilterSeparable()](http://ermig1979.github.io/Simd/help/group__face__recognition.html#ga59f186f7578a091b31dd568a0a92ad23) to perform the same action. As known Gaussian filter is a separable filter: 

    exp(-(x^2 + y^2)/q^2) = exp(-x^2/q^2)*exp(-y^2/q^2).
