### ISSUE TITLE
Error while solution buiding in VS 2019: Error C3861 '_pext_u64': identifier not found	in Sse41	

### ISSUE THREAD

**Issue by zielony71** [ermig1979/Simd#150]
Hello!

I've got this error (10 times) while buiding the solution in VS 2019: 

Error C3861 '_pext_u64': identifier not found	(in Sse41	project)

Can anybody figure out what is wrong ?

**Comment by ermig1979** [comment]
Hello. Is this Win32 or x64 build platform?

**Comment by zielony71** [comment]
Right, I haven't choosen a proper configuration in VS: it should be **x64** for my computer (instead of Win32). After doing that the everything has been compiled without any issues.
Thank you very much for answering and for that great library!

**Comment by zielony71** [comment]
Issue is solved.
