### ISSUE TITLE
`-oh=log.html` creates an empty directory instead of writing to log.html

### ISSUE THREAD

**Issue by ngzhian** [ermig1979/Simd#153]
I just tried building with defaults and running: `Test -fi=Yuv420pToBgra -oh=log.html`. It creates a empty director log.html.

Same with `-ot=log.txt` it also creates an empty directory log.txt.

**Comment by ermig1979** [comment]
Thank you for bug report! The error was fixed.

**Comment by ngzhian** [comment]
Checked that this is fixed by a51408c74f93c22652d57506b7909c0f3c59328a, thanks!
