### ISSUE TITLE
Rotate image

### ISSUE THREAD

**Issue by rogerou** [ermig1979/Simd#16]
Hi,
how can i rotate image  with Simd?
Thanks.!

**Comment by ermig1979** [comment]
Hello.

Unfortunately Simd Library hasn't any tools to rotate image.

Ihar.

**Comment by ermig1979** [comment]
It is possible. I will do it.

**Comment by kotc** [comment]
maybe while you are at it, how about vertical/horizontal flip? or shall i ask in new issue

**Comment by ermig1979** [comment]
Vertical flip is simple: 
  
    Simd::Copy(src.Flipped(), dst);

**Comment by martin-etchart** [comment]
Did you have any chance to work on the +/-90 rotation? A single transpose would work for what I need. Thanks!

**Comment by ermig1979** [comment]
I have started to solve this issue.

**Comment by ermig1979** [comment]
I have added base version of function TransfromImage. Optimizations will be soon.
