### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by shersoni610** [ermig1979/Simd#160]
Hello,

On Mac mini machine, I get the following compilation error:
Simd/prj/cmake/../../src/Simd/SimdImageSaveJpeg.h:173:23: error: non-const lvalue reference to type 'uint64_t' (aka 'unsigned long long') cannot bind to a value of unrelated type 'size_t' (aka 'unsigned long')
            uint64_t &bitBuffer = stream.BitBuffer();

Can someone help?

**Comment by ermig1979** [comment]
Hello!

Thank you for bug report. I tried to solve this trouble and did some changes. 
But I can't get access to Mac mini and check is this fixes the bug? 
Would you verify resolving of this bug on the target platform.

**Comment by shersoni610** [comment]
One more issue:
In file included from /Users/csverma/Projects/Avail/Simd/src/Test/TestFile.cpp:24:
/home/Simd/prj/cmake/../../src/Test/TestFile.h:49:16: error: expected expression
        return return String("");
               ^

**Comment by ermig1979** [comment]
The second bug is fixed too. Are there any errors else?

**Comment by shersoni610** [comment]
Thank you very much. The code compiles without any glitches on a Mac machine. However, one test fails.

Are there any benchmark results compared to Intel IPP?

Thanks

**Comment by ermig1979** [comment]
There are no special tests which compare Simd an Intel IPP. But of course there is opportunity to compare performance manualy.
