### ISSUE TITLE
Image as ROI Mask

### ISSUE THREAD

**Issue by trlsmax** [ermig1979/Simd#163]
Is there a way to use an image, like mask.bmp, as a ROI mask in motion detector?
Or do we have to find contour in the mask.bmp and set it in model ?

**Comment by ermig1979** [comment]
Hi! There is no such feature now. But I can add it if it will necessary.

**Comment by ermig1979** [comment]
I added this feature.

**Comment by trlsmax** [comment]
Wow! Super fast. 
Thank you.
This will really help if I run my code on raspberry pi.
