### ISSUE TITLE
SimdAvx512bwBgraToBgr.cpp - MSVC 2017 build errors

### ISSUE THREAD

**Issue by ArsMasiuk** [ermig1979/Simd#165]
Hi,
there is a problem building SimdAvx512bwBgraToBgr.cpp under MSVC 2017 64 bit:

1>Compiling...
1>SimdAvx512bwBgraToBgr.cpp
1>d:\tmp\simd\src\simd\simdavx512bwbgratobgr.cpp(160): warning C4002: too many arguments for function-like macro invocation '_mm512_shuffle_epi8'
1>d:\tmp\simd\src\simd\simdavx512bwbgratobgr.cpp(160): error C2059: syntax error: ')'
1>d:\tmp\simd\src\simd\simdavx512bwbgratobgr.cpp(177): note: see reference to function template instantiation 'void Simd::Avx512bw::BgraToRgba<true,false>(const uint8_t *,uint8_t *,__mmask64)' being compiled
1>d:\tmp\simd\src\simd\simdavx512bwbgratobgr.cpp(188): note: see reference to function template instantiation 'void Simd::Avx512bw::BgraToRgba<true>(const uint8_t *,size_t,size_t,size_t,uint8_t *,size_t)' being compiled
1>d:\tmp\simd\src\simd\simdavx512bwbgratobgr.cpp(160): warning C4804: '>': unsafe use of type 'bool' in operation
1>d:\tmp\simd\src\simd\simdavx512bwbgratobgr.cpp(160): error C2059: syntax error: ';'
1>d:\tmp\simd\src\simd\simdavx512bwbgratobgr.cpp(161): error C2143: syntax error: missing ';' before '}'
1>d:\tmp\simd\src\simd\simdavx512bwbgratobgr.cpp(159): error C2143: syntax error: missing ';' before '{'
1>c:\program files (x86)\microsoft visual studio\2017\wdexpress\vc\tools\msvc\14.16.27023\include\type_traits(1573): error C2143: syntax error: missing ';' before '{'
1>c:\program files (x86)\microsoft visual studio\2017\wdexpress\vc\tools\msvc\14.16.27023\include\type_traits(1574): error C2947: expecting '>' to terminate template-argument-list, found '<'
1>c:\program files (x86)\microsoft visual studio\2017\wdexpress\vc\tools\msvc\14.16.27023\include\type_traits(1574): error C2146: syntax error: missing ')' before identifier '_Ty'
1>c:\program files (x86)\microsoft visual studio\2017\wdexpress\vc\tools\msvc\14.16.27023\include\type_traits(1574): error C2065: '_Ty': undeclared identifier
1>c:\program files (x86)\microsoft visual studio\2017\wdexpress\vc\tools\msvc\14.16.27023\include\type_traits(1574): error C2059: syntax error: '>'
1>c:\program files (x86)\microsoft visual studio\2017\wdexpress\vc\tools\msvc\14.16.27023\include\type_traits(1574): error C2947: expecting '>' to terminate template-argument-list, found '>'
1>c:\program files (x86)\microsoft visual studio\2017\wdexpress\vc\tools\msvc\14.16.27023\include\type_traits(1574): error C2061: syntax error: identifier '_Arg'
1>c:\program files (x86)\microsoft visual studio\2017\wdexpress\vc\tools\msvc\14.16.27023\include\type_traits(1574): error C2143: syntax error: missing ')' before ';'
1>c:\program files (x86)\microsoft visual studio\2017\wdexpress\vc\tools\msvc\14.16.27023\include\type_traits(1575): error C2143: syntax error: missing ';' before '}'
1>c:\program files (x86)\microsoft visual studio\2017\wdexpress\vc\tools\msvc\14.16.27023\include\xutility(285): error C2065: '_Other1': undeclared identifier
1>c:\program files (x86)\microsoft visual studio\2017\wdexpress\vc\tools\msvc\14.16.27023\include\xutility(286): error C2065: '_Other2': undeclared identifier
1>c:\program files (x86)\microsoft visual studio\2017\wdexpress\vc\tools\msvc\14.16.27023\include\xutility(286): error C2065: '_Val2': undeclared identifier
1>c:\program files (x86)\microsoft visual studio\2017\wdexpress\vc\tools\msvc\14.16.27023\include\xutility(286): error C3546: '...': there are no parameter packs available to expand
1>c:\program files (x86)\microsoft visual studio\2017\wdexpress\vc\tools\msvc\14.16.27023\include\xutility(286): error C3861: '_Myval2': identifier not found
1>c:\program files (x86)\microsoft visual studio\2017\wdexpress\vc\tools\msvc\14.16.27023\include\xutility(286): error C2065: '_Myval2': undeclared identifier
1>d:\tmp\simd\src\simd\simdavx512bwbgratobgr.cpp(195): error C2059: syntax error: '<end Parse>'

**Comment by ermig1979** [comment]
Hi! Thank you for bug report! The bug has been fixed.
