### ISSUE TITLE
CLang-cl (12.0.0) build problem on Windows 10 64bit

### ISSUE THREAD

**Issue by ArsMasiuk** [ermig1979/Simd#166]
lines like #include <Simd/SimdDefs.h> lead to bunch of compiler errors:

In file included from C:\Work\Test\End.Expert.V2.Clang\Code\ExtLibs_Include\simd-4.8.103\Simd/SimdMemory.h:29:
In file included from C:\Work\Test\End.Expert.V2.Clang\Code\ExtLibs_Include\simd-4.8.103\Simd/SimdMath.h:29:
C:\Work\Test\End.Expert.V2.Clang\Code\ExtLibs_Include\simd-4.8.103\Simd/SimdConst.h(93,32): error: excess elements in vector initializer
        const __m128i K_ZERO = SIMD_MM_SET1_EPI8(0);
                               ^~~~~~~~~~~~~~~~~~~~
C:\Work\Test\End.Expert.V2.Clang\Code\ExtLibs_Include\simd-4.8.103\Simd/SimdInit.h(104,40): note: expanded from macro 'SIMD_MM_SET1_EPI8'
    {SIMD_AS_CHAR(a), SIMD_AS_CHAR(a), SIMD_AS_CHAR(a), SIMD_AS_CHAR(a), \
                                       ^~~~~~~~~~~~~~~
C:\Work\Test\End.Expert.V2.Clang\Code\ExtLibs_Include\simd-4.8.103\Simd/SimdInit.h(38,25): note: expanded from macro 'SIMD_AS_CHAR'
#define SIMD_AS_CHAR(a) char(a)
                        ^~~~~~~
In file included from ..\CSimdRgbToGrayProcessorComp.cpp:1:
In file included from ..\..\..\Include\qsimd/CSimdRgbToGrayProcessorComp.h:14:
In file included from C:\Work\Test\End.Expert.V2.Clang\Code\ExtLibs_Include\simd-4.8.103\Simd/SimdMemory.h:29:
In file included from C:\Work\Test\End.Expert.V2.Clang\Code\ExtLibs_Include\simd-4.8.103\Simd/SimdMath.h:29:
C:\Work\Test\End.Expert.V2.Clang\Code\ExtLibs_Include\simd-4.8.103\Simd/SimdConst.h(94,36): error: excess elements in vector initializer
        const __m128i K_INV_ZERO = SIMD_MM_SET1_EPI8(0xFF);
                                   ^~~~~~~~~~~~~~~~~~~~~~~
C:\Work\Test\End.Expert.V2.Clang\Code\ExtLibs_Include\simd-4.8.103\Simd/SimdInit.h(104,40): note: expanded from macro 'SIMD_MM_SET1_EPI8'
    {SIMD_AS_CHAR(a), SIMD_AS_CHAR(a), SIMD_AS_CHAR(a), SIMD_AS_CHAR(a), \
                                       ^~~~~~~~~~~~~~~
C:\Work\Test\End.Expert.V2.Clang\Code\ExtLibs_Include\simd-4.8.103\Simd/SimdInit.h(38,25): note: expanded from macro 'SIMD_AS_CHAR'
#define SIMD_AS_CHAR(a) char(a)
                        ^~~~~~~

**Comment by ermig1979** [comment]
Thank you for bug report! I think that fixed this error, but I need independent confirmation. Could you check?
