### ISSUE TITLE
inlcuding simd in CMakeLists

### ISSUE THREAD

**Issue by fredy1221** [ermig1979/Simd#167]
Hello,
Is there a way to integrate simd in my CMakeLists.txt file ?
I'm running on nvidia jetson xavier agx

**Comment by ermig1979** [comment]
Hello.

There is an example of integration Simd in third party project: 

https://github.com/ermig1979/Synet/blob/master/prj/cmake/CMakeLists.txt

I hope that it will help you.

**Comment by fredy1221** [comment]
Thanks for your reply,
I tried adding the part:
```
if(SIMD)
	set(SIMD_TEST OFF CACHE BOOL "" FORCE)
	set(SIMD_SHARED ON CACHE BOOL "" FORCE)
	set(SIMD_GET_VERSION OFF CACHE BOOL "" FORCE)
	set(SIMD_TOOLCHAIN ${CMAKE_CXX_COMPILER})
	set(SIMD_INFO ${SYNET_INFO} CACHE BOOL "" FORCE)
	set(SIMD_LIB "Simd")	
	
	set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
	add_definitions(-DSYNET_SIMD_LIBRARY_ENABLE)
	add_subdirectory(/home/oreyeon/tkDNN/include/Simd/prj/cmake /home/oreyeon/tkDNN/include/Simd)

endif()
```
and added `target_link_libraries(bayerconv tkDNN ${SIMD_LIB})`
but when I make the file is still get:
```
fatal error: Simd: No such file or directory
 #include <Simd>
```

Simd folder is placed in the directory include which also has tkDNNm, cpp files are in another directory.

**Comment by ermig1979** [comment]
You forgot add:

    	include_directories($/home/oreyeon/tkDNN/include/Simd/src)

**Comment by fredy1221** [comment]
it's still not working

**Comment by ermig1979** [comment]
fatal error: Simd: No such file or directory
     #include <Simd>

There is no file with name 'Simd' . You have to include SimdLib.h or SimdLib.hpp.

**Comment by fredy1221** [comment]
it worked thank you!
