### ISSUE TITLE
SIMD_OPENCV_ENABLE issue

### ISSUE THREAD

**Issue by ArttuLe** [ermig1979/Simd#168]
Hello,

I'm trying to use the library with OpenCV on a Jetson Nano project of mine, but when I define the OPENCV_ENABLE macro I get undefined references to all my OpenCV functions. 

The tests run successfully after building the library, and I get no errors regarding not linking the library properly etc. when I have the macro undefined, but when I define the macro, I get the undefined references. Do you know what might be causing it?

Thanks in advance.

**Comment by ermig1979** [comment]
Hello. 
Did you add linker reference in the your project to OpenCV library? 
The macro OPENCV ENABLE enables code of interaction between Simd and OpenCV and requires additional references to OpenCV for linker.

**Comment by ArttuLe** [comment]
No i didn't, Now it's working.

Thank you!
