### ISSUE TITLE
Affine Image Transformation

### ISSUE THREAD

**Issue by olokobayusuf** [ermig1979/Simd#170]
Hey @ermig1979 , following from our convo I'm opening this issue for implementing a generalized affine image transformation API. This function will be capable of expressing an entire family of geometric image transformations. The downside is that it would typically result in unordered memory accesses, and might not be trivially parallelizable. I'll update this issue with a proposal API, and will create a fork with a simple (un-parallelized) C/C++ implementation. Looking forward to what we can do on this!

**Comment by ermig1979** [comment]
Ok. I'm waiting for API and scalar implementation.

**Comment by ermig1979** [comment]
I added function Simd::WarpAffine.

**Comment by olokobayusuf** [comment]
@ermig1979 thanks for this. We ended up going with a very naive implementation, and turns out `clang` did a good job at auto-vectorizing with `-O3`. I'm looking forward to profiling your implementation. I truly cannot thank you enough for this project; we're [massive fans at NatML](https://docs.natml.ai/natml/insiders/oss#mit-license).
