### ISSUE TITLE
resize inplace

### ISSUE THREAD

**Issue by zhiboniu** [ermig1979/Simd#171]
Hi,

 I want to resize the images inplace by this :
cv::resize(*img, *img, cv::Size(resized_width[0],resized_height), 0, 0, 0);

But I notice that the arguments of Simd::ResizeBilinear(src, dst) have to be different。How can I achieve the inplace version by simd?

Thankyou very much!

**Comment by ermig1979** [comment]
I think that it will be look as:

    Simd::View tmp(newSize, src.format);
    Simd::ResizeBilinear(src, tmp);
    src.Swap(tmp);
