### ISSUE TITLE
is there any method to watch that simd is working?

### ISSUE THREAD

**Issue by jcyhcs** [ermig1979/Simd#172]
hi,professor:
i used your library on nvidia jetson platform for accelerate image processing , for example: resize , color space convert. those function work in my code, and i want to have a method that can watch the accelerator is working, just like JTOP tools can give that GPU was used with a chart, so , which tools can i use? or which method?
please help!

**Comment by ermig1979** [comment]
Hi! 

The library has method Simd::PrintInfo which prints system information about SIMD extensions used on current platform.

If you want to receive more detail information about acceleration received with Simd Library I would recommend to run Simd tests (see Test application).

 An example to run tests:

    ./Test -m=a -tt=1

And you will receive a table with information about functions acceleration (see last columns).
