### ISSUE TITLE
Test failed

### ISSUE THREAD

**Issue by oniliste** [ermig1979/Simd#173]
@ermig1979 Hello , I find some failed test on version 4.9.104

OS: Windows 10 , compiler: VS2015

Win32 Debug failed tests:
VectorNormNp16fAutoTest
CosineDistance16fAutoTest crashed at 3rd sub-test (after canceled VectorNormNp16fAutoTest)
SynetScale8iForwardAutoTest

Win32 Release failed tests:
 VectorNormNp16fAutoTest

X64 Debug failed tests:
VectorNormNp16fAutoTest

**Comment by ermig1979** [comment]
Thank you for bug report! I will check it and fix.
