### ISSUE TITLE
SimdResizerInit overhead?

### ISSUE THREAD

**Issue by mikeversteeg** [ermig1979/Simd#187]
Should I assume SimdResizerInit/SimdRelease adds noticeable overhead to SimdResizerRun, which is the reason it is not combined into one function? I have a function called by many threads which (also) resizes an YUV bitmap, and each call may require different sizes. I'm wondering how best to implement this.

**Comment by ermig1979** [comment]
SimdResizerInit creates precalculated resize coefficients for current sizes of input and output image. 
SimdResizerInit ~ dstH + dstW, SimdResizerRun ~ dstH * dstW.
Separation of SimdResizerInit/SimdRelease/SimdResizerRun is mainly useful for video processing.

**Comment by mikeversteeg** [comment]
I don't understand. If it's a simple calculation then I assume there is no noticeable overhead in calculating this every time (especially with HD video) and so this could be just one function? I thought maybe there was some time consuming table construction going on..

**Comment by ermig1979** [comment]
Of course it can be one function. For example see function Simd::Resize :

    template<template<class> class A> SIMD_INLINE void Resize(const View<A> & src, View<A> & dst, ::SimdResizeMethodType method = ::SimdResizeMethodBilinear)
    {
        assert(src.format == dst.format && (src.format == View<A>::Float || src.ChannelSize() == 1));

        if (EqualSize(src, dst))
        {
            Copy(src, dst);
        }
        else
        {
            SimdResizeChannelType type = src.format == View<A>::Float ? SimdResizeChannelFloat : SimdResizeChannelByte;
            void * resizer = SimdResizerInit(src.width, src.height, dst.width, dst.height, src.ChannelCount(), type, method);
            if (resizer)
            {
                SimdResizerRun(resizer, src.data, src.stride, dst.data, dst.stride);
                SimdRelease(resizer);
            }
            else
                assert(0);
        }
    }
