### ISSUE TITLE
Resize methods

### ISSUE THREAD

**Issue by mikeversteeg** [ermig1979/Simd#189]
I've been trying out the various resize methods in Windows 10 (YUV420/HD) and came to the following conclusions..

SimdResizeMethodNearest
Fast, bbut when scaling down to less than 25% some images look awful (lines disappear).

SimdResizeMethodNearestPytorch
Somewhat better, but still useless for less than 25%.

SimdResizeMethodBilinear
Big improvement with hardly more CPU usage.

SimdResizeMethodBilinearCaffe
SimdResizeMethodBilinearPytorch
Do not work.

SimdResizeMethodArea
Very nice, but CPU usage doubles.

So there's no perfect solution. I thought dynamically picking the method based  on the amount of scaling would work, but even when resizing to 20% of original SimdResizeMethodArea still uses around 50% more CPU. I'm very curious of the results of SimdResizeMethodBilinearCaffe and SimdResizeMethodBilinearPytorch for <25% scaling but they give garbled video.

**Comment by ermig1979** [comment]
It is my mistake. SimdResizeMethodBilinearCaffe and SimdResizeMethodBilinearPytorch work obly with float image. I forgot to note this in docs. The methods are need for compatibility (as and SimdResizeMethodNearestPytorch). I would to reccomend to use (SimdResizeMethodNearest, SimdResizeMethodBilinear, SimdResizeMethodArea) methods.
SimdResizeMethodArea is designed to large reduce image.

**Comment by ermig1979** [comment]
I have plan to add Bicubic interpolation.

**Comment by mikeversteeg** [comment]
I'm looking forward trying out Bicubic!
