### ISSUE TITLE
Build errors. ARM native build.

### ISSUE THREAD

**Issue by dvl36** [ermig1979/Simd#2]
Linux(Debian Wheezy), gcc/g++ -4.7, using cmake:
[...]
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp: In instantiation of ‘void Simd::Neon::AlphaBlender<align, 3u>::operator()(const uint8_t*, uint8_t*, uint8x16_t) [with bool align = true; uint8_t = unsigned char; uint8x16_t = __vector(16) __builtin_neon_uqi]’:
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:125:21:   required from ‘void Simd::Neon::AlphaBlending(const uint8_t*, size_t, size_t, size_t, const uint8_t*, size_t, uint8_t*, size_t) [with bool align = true; unsigned int channelCount = 3u; uint8_t = unsigned char; size_t = unsigned int]’
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:153:13:   required from ‘void Simd::Neon::AlphaBlending(const uint8_t*, size_t, size_t, size_t, size_t, const uint8_t*, size_t, uint8_t*, size_t) [with bool align = true; uint8_t = unsigned char; size_t = unsigned int]’
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:164:104:   required from here
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:98:5: error: no matching function for call to ‘AlphaBlending(const uint8_t*, uint8_t*, <brace-enclosed initializer list>)’
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:98:5: note: candidates are:
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:38:42: note: template<bool align> void Simd::Neon::AlphaBlending(const uint8_t*, uint8_t*, uint8x8x2_t)
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:38:42: note:   template argument deduction/substitution failed:
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:98:5: note:   cannot convert ‘{vtbl1_u8(_alpha.uint8x8x2_t::val[0], ((uint8x8_t)Simd::Neon::K8_TBL1_3_0)), vtbl1_u8(_alpha.uint8x8x2_t::val[0], ((uint8x8_t)Simd::Neon::K8_TBL1_3_1))}’ (type ‘<brace-enclosed initializer list>’) to type ‘uint8x8x2_t’
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:47:51: note: template<int part> uint8x8_t Simd::Neon::AlphaBlending(const uint8x16_t&, const uint8x16_t&, const uint8x16_t&, const uint8x16_t&)
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:47:51: note:   template argument deduction/substitution failed:
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:98:5: note:   cannot convert ‘src’ (type ‘const uint8_t* {aka const unsigned char*}’) to type ‘const uint8x16_t& {aka const __vector(16) __builtin_neon_uqi&}’
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:56:48: note: template<bool align> void Simd::Neon::AlphaBlending(const uint8_t*, uint8_t*, const uint8x16_t&)
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:56:48: note:   template argument deduction/substitution failed:
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:98:5: note:   cannot convert ‘{vtbl1_u8(_alpha.uint8x8x2_t::val[0], ((uint8x8_t)Simd::Neon::K8_TBL1_3_0)), vtbl1_u8(_alpha.uint8x8x2_t::val[0], ((uint8x8_t)Simd::Neon::K8_TBL1_3_1))}’ (type ‘<brace-enclosed initializer list>’) to type ‘const uint8x16_t& {aka const __vector(16) __builtin_neon_uqi&}’
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:99:5: error: no matching function for call to ‘AlphaBlending(const uint8_t*, uint8_t*, <brace-enclosed initializer list>)’
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:99:5: note: candidates are:
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:38:42: note: template<bool align> void Simd::Neon::AlphaBlending(const uint8_t*, uint8_t*, uint8x8x2_t)
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:38:42: note:   template argument deduction/substitution failed:
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:99:5: note:   cannot convert ‘{vtbl1_u8(_alpha.uint8x8x2_t::val[0], ((uint8x8_t)Simd::Neon::K8_TBL1_3_2)), vtbl1_u8(_alpha.uint8x8x2_t::val[1], ((uint8x8_t)Simd::Neon::K8_TBL1_3_0))}’ (type ‘<brace-enclosed initializer list>’) to type ‘uint8x8x2_t’
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:47:51: note: template<int part> uint8x8_t Simd::Neon::AlphaBlending(const uint8x16_t&, const uint8x16_t&, const uint8x16_t&, const uint8x16_t&)
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:47:51: note:   template argument deduction/substitution failed:
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:99:5: note:   cannot convert ‘(src + 16u)’ (type ‘const uint8_t* {aka const unsigned char*}’) to type ‘const uint8x16_t& {aka const __vector(16) __builtin_neon_uqi&}’
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:56:48: note: template<bool align> void Simd::Neon::AlphaBlending(const uint8_t*, uint8_t*, const uint8x16_t&)
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:56:48: note:   template argument deduction/substitution failed:
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:99:5: note:   cannot convert ‘{vtbl1_u8(_alpha.uint8x8x2_t::val[0], ((uint8x8_t)Simd::Neon::K8_TBL1_3_2)), vtbl1_u8(_alpha.uint8x8x2_t::val[1], ((uint8x8_t)Simd::Neon::K8_TBL1_3_0))}’ (type ‘<brace-enclosed initializer list>’) to type ‘const uint8x16_t& {aka const __vector(16) __builtin_neon_uqi&}’
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:100:5: error: no matching function for call to ‘AlphaBlending(const uint8_t*, uint8_t*, <brace-enclosed initializer list>)’
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:100:5: note: candidates are:
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:38:42: note: template<bool align> void Simd::Neon::AlphaBlending(const uint8_t*, uint8_t*, uint8x8x2_t)
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:38:42: note:   template argument deduction/substitution failed:
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:100:5: note:   cannot convert ‘{vtbl1_u8(_alpha.uint8x8x2_t::val[1], ((uint8x8_t)Simd::Neon::K8_TBL1_3_1)), vtbl1_u8(_alpha.uint8x8x2_t::val[1], ((uint8x8_t)Simd::Neon::K8_TBL1_3_2))}’ (type ‘<brace-enclosed initializer list>’) to type ‘uint8x8x2_t’
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:47:51: note: template<int part> uint8x8_t Simd::Neon::AlphaBlending(const uint8x16_t&, const uint8x16_t&, const uint8x16_t&, const uint8x16_t&)
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:47:51: note:   template argument deduction/substitution failed:
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:100:5: note:   cannot convert ‘(src + 32u)’ (type ‘const uint8_t* {aka const unsigned char*}’) to type ‘const uint8x16_t& {aka const __vector(16) __builtin_neon_uqi&}’
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:56:48: note: template<bool align> void Simd::Neon::AlphaBlending(const uint8_t*, uint8_t*, const uint8x16_t&)
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:56:48: note:   template argument deduction/substitution failed:
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:100:5: note:   cannot convert ‘{vtbl1_u8(_alpha.uint8x8x2_t::val[1], ((uint8x8_t)Simd::Neon::K8_TBL1_3_1)), vtbl1_u8(_alpha.uint8x8x2_t::val[1], ((uint8x8_t)Simd::Neon::K8_TBL1_3_2))}’ (type ‘<brace-enclosed initializer list>’) to type ‘const uint8x16_t& {aka const __vector(16) __builtin_neon_uqi&}’
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp: In instantiation of ‘void Simd::Neon::AlphaBlender<align, 3u>::operator()(const uint8_t*, uint8_t*, uint8x16_t) [with bool align = false; uint8_t = unsigned char; uint8x16_t = __vector(16) __builtin_neon_uqi]’:
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:130:21:   required from ‘void Simd::Neon::AlphaBlending(const uint8_t*, size_t, size_t, size_t, const uint8_t*, size_t, uint8_t*, size_t) [with bool align = true; unsigned int channelCount = 3u; uint8_t = unsigned char; size_t = unsigned int]’
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:153:13:   required from ‘void Simd::Neon::AlphaBlending(const uint8_t*, size_t, size_t, size_t, size_t, const uint8_t*, size_t, uint8_t*, size_t) [with bool align = true; uint8_t = unsigned char; size_t = unsigned int]’
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:164:104:   required from here
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:98:5: error: no matching function for call to ‘AlphaBlending(const uint8_t*, uint8_t*, <brace-enclosed initializer list>)’
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:98:5: note: candidates are:
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:38:42: note: template<bool align> void Simd::Neon::AlphaBlending(const uint8_t*, uint8_t*, uint8x8x2_t)
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:38:42: note:   template argument deduction/substitution failed:
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:98:5: note:   cannot convert ‘{vtbl1_u8(_alpha.uint8x8x2_t::val[0], ((uint8x8_t)Simd::Neon::K8_TBL1_3_0)), vtbl1_u8(_alpha.uint8x8x2_t::val[0], ((uint8x8_t)Simd::Neon::K8_TBL1_3_1))}’ (type ‘<brace-enclosed initializer list>’) to type ‘uint8x8x2_t’
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:47:51: note: template<int part> uint8x8_t Simd::Neon::AlphaBlending(const uint8x16_t&, const uint8x16_t&, const uint8x16_t&, const uint8x16_t&)
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:47:51: note:   template argument deduction/substitution failed:
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:98:5: note:   cannot convert ‘src’ (type ‘const uint8_t* {aka const unsigned char*}’) to type ‘const uint8x16_t& {aka const __vector(16) __builtin_neon_uqi&}’
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:56:48: note: template<bool align> void Simd::Neon::AlphaBlending(const uint8_t*, uint8_t*, const uint8x16_t&)
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:56:48: note:   template argument deduction/substitution failed:
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:98:5: note:   cannot convert ‘{vtbl1_u8(_alpha.uint8x8x2_t::val[0], ((uint8x8_t)Simd::Neon::K8_TBL1_3_0)), vtbl1_u8(_alpha.uint8x8x2_t::val[0], ((uint8x8_t)Simd::Neon::K8_TBL1_3_1))}’ (type ‘<brace-enclosed initializer list>’) to type ‘const uint8x16_t& {aka const __vector(16) __builtin_neon_uqi&}’
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:99:5: error: no matching function for call to ‘AlphaBlending(const uint8_t*, uint8_t*, <brace-enclosed initializer list>)’
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:99:5: note: candidates are:
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:38:42: note: template<bool align> void Simd::Neon::AlphaBlending(const uint8_t*, uint8_t*, uint8x8x2_t)
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:38:42: note:   template argument deduction/substitution failed:
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:99:5: note:   cannot convert ‘{vtbl1_u8(_alpha.uint8x8x2_t::val[0], ((uint8x8_t)Simd::Neon::K8_TBL1_3_2)), vtbl1_u8(_alpha.uint8x8x2_t::val[1], ((uint8x8_t)Simd::Neon::K8_TBL1_3_0))}’ (type ‘<brace-enclosed initializer list>’) to type ‘uint8x8x2_t’
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:47:51: note: template<int part> uint8x8_t Simd::Neon::AlphaBlending(const uint8x16_t&, const uint8x16_t&, const uint8x16_t&, const uint8x16_t&)
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:47:51: note:   template argument deduction/substitution failed:
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:99:5: note:   cannot convert ‘(src + 16u)’ (type ‘const uint8_t* {aka const unsigned char*}’) to type ‘const uint8x16_t& {aka const __vector(16) __builtin_neon_uqi&}’
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:56:48: note: template<bool align> void Simd::Neon::AlphaBlending(const uint8_t*, uint8_t*, const uint8x16_t&)
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:56:48: note:   template argument deduction/substitution failed:
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:99:5: note:   cannot convert ‘{vtbl1_u8(_alpha.uint8x8x2_t::val[0], ((uint8x8_t)Simd::Neon::K8_TBL1_3_2)), vtbl1_u8(_alpha.uint8x8x2_t::val[1], ((uint8x8_t)Simd::Neon::K8_TBL1_3_0))}’ (type ‘<brace-enclosed initializer list>’) to type ‘const uint8x16_t& {aka const __vector(16) __builtin_neon_uqi&}’
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:100:5: error: no matching function for call to ‘AlphaBlending(const uint8_t*, uint8_t*, <brace-enclosed initializer list>)’
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:100:5: note: candidates are:
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:38:42: note: template<bool align> void Simd::Neon::AlphaBlending(const uint8_t*, uint8_t*, uint8x8x2_t)
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:38:42: note:   template argument deduction/substitution failed:
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:100:5: note:   cannot convert ‘{vtbl1_u8(_alpha.uint8x8x2_t::val[1], ((uint8x8_t)Simd::Neon::K8_TBL1_3_1)), vtbl1_u8(_alpha.uint8x8x2_t::val[1], ((uint8x8_t)Simd::Neon::K8_TBL1_3_2))}’ (type ‘<brace-enclosed initializer list>’) to type ‘uint8x8x2_t’
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:47:51: note: template<int part> uint8x8_t Simd::Neon::AlphaBlending(const uint8x16_t&, const uint8x16_t&, const uint8x16_t&, const uint8x16_t&)
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:47:51: note:   template argument deduction/substitution failed:
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:100:5: note:   cannot convert ‘(src + 32u)’ (type ‘const uint8_t* {aka const unsigned char*}’) to type ‘const uint8x16_t& {aka const __vector(16) __builtin_neon_uqi&}’
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:56:48: note: template<bool align> void Simd::Neon::AlphaBlending(const uint8_t*, uint8_t*, const uint8x16_t&)
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:56:48: note:   template argument deduction/substitution failed:
/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp:100:5: note:   cannot convert ‘{vtbl1_u8(_alpha.uint8x8x2_t::val[1], ((uint8x8_t)Simd::Neon::K8_TBL1_3_1)), vtbl1_u8(_alpha.uint8x8x2_t::val[1], ((uint8x8_t)Simd::Neon::K8_TBL1_3_2))}’ (type ‘<brace-enclosed initializer list>’) to type ‘const uint8x16_t& {aka const __vector(16) __builtin_neon_uqi&}’
make[2]: *** [CMakeFiles/SimdNeon.dir/root/Simd/src/Simd/SimdNeonAlphaBlending.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/SimdNeon.dir/all] Error 2
make: *** [all] Error 2

**Comment by ermig1979** [comment]
The error was caused using of old computer. It does not support initialization in style of C++11. I fixed this bug.
