### ISSUE TITLE
lbp detection training data

### ISSUE THREAD

**Issue by srikanthreddybethi** [ermig1979/Simd#20]
@ermig1979 
can you please let me know what is the data set you have used to train lbp face detector?

**Comment by srikanthreddybethi** [comment]
And do you have any bench marking results against http://vis-www.cs.umass.edu/fddb/ ?

**Comment by ermig1979** [comment]
Hello. The standard OpenCV LBP cascade is used in Simd Library as an example. In order to train LBP cascade you have to use OpenCV training tools.

P.S. For my purposes I have trained LBP and HAAR cascades (but it was car number detection). I used my own collection of training photos.
