### ISSUE TITLE
Bug in SimdResizeMethodNearest resizer

### ISSUE THREAD

**Issue by mikeversteeg** [ermig1979/Simd#202]
Calling `SimdResizerRun `with `SimdResizeMethodNearest `gives spill on the right of the resized image. E.g. if I have two YUV420P images of 1920*1080 and copy one to the first quadrant of the other (0, 0, 960, 540), there is spill to the right. See image. This does not happen with `SimdResizeMethodArea `or `SimdResizeMethodBilinear `(did not try others) but (very!) unfortunately they are too slow.
SimdLib v4.9.111.
Windows 64
![image](https://user-images.githubusercontent.com/46790724/159679231-62775704-9a3c-4ee6-880a-74d2a0d03ce2.png)

**Comment by ermig1979** [comment]
Hello!
I have some questions:
1) Is it a source or result image?
2) Could you give code to illustate of the bug.

**Comment by mikeversteeg** [comment]
1. The spill is in the target/result image.
2.
```
void *rcy, *rcu, *rcv;
rcy = SimdResizerInit(sr.Width(), sr.Height(), tr.Width(), tr.Height(), 1, SimdResizeChannelByte, SimdResizeMethodNearest);
if (rcy) {
  SimdResizerRun(rcy, syuv+sr.Left+sr.Top*sw, sw, tyuv+tr.Left+tr.Top*tw, tw);
  SimdRelease(rcy);
}
rcu = SimdResizerInit(sr.Width()/2, sr.Height()/2, tr.Width()/2, tr.Height()/2, 1, SimdResizeChannelByte, SimdResizeMethodNearest);
if (rcu) {
  SimdResizerRun(rcu, syuv+sw*sh + sr.Left/2+sr.Top*sw/2, sw/2, tyuv+tw*th + tr.Left/2+tr.Top/2*tw/2, tw/2);
  SimdRelease(rcu);
}
rcv = SimdResizerInit(sr.Width()/2, sr.Height()/2, tr.Width()/2, tr.Height()/2, 1, SimdResizeChannelByte, SimdResizeMethodNearest);
if (rcv) {
  SimdResizerRun(rcv, syuv+sw*sh*5/4 + sr.Left/2+sr.Top*sw/2, sw/2, tyuv+tw*th*5/4 + tr.Left/2+tr.Top/2*tw/2, tw/2);
  SimdRelease(rcv);
}

```

**Comment by ermig1979** [comment]
I added test ResizeYuv420pSpecialTest() to TestResize.cpp.

./Test -m=s -fi=ResizeYuv420p -w=1920 -h=1080

Src image:
![src](https://user-images.githubusercontent.com/11633100/160093898-647579ed-7b05-47d8-b88b-7142b18c643c.jpg)

Вые image:
![dst](https://user-images.githubusercontent.com/11633100/160093984-32804e9d-8f12-4740-a370-06741d301616.jpg)

Green background value in output image is result of Simd::Fill(yuvDst, 0);

**Comment by mikeversteeg** [comment]
Note the spill is green so won't show up in this test. Also note it is only with nearest filter, if I replace the filter in my code with e.g. area then the bug is gone.

**Comment by ermig1979** [comment]
Can this spill is consequence of using of uninitialized memory in the output or input image?

**Comment by mikeversteeg** [comment]
No. Do you understand this only happens with `SimdResizeMethodNearest`? Spill is always beyond target line and green so it will not show up in your test. Maybe it is also exclusive to Windows 64, I cannot confirm.

**Comment by mikeversteeg** [comment]
I tested again all 4 resize methods ((Nearest, Bilinear, Bicubic, Area) and can confirm only Nearest has this bug. If it's not a bug then maybe I misunderstood the documentation and my code is wrong, but it's remarkable the other 3 methods work flawlessly.

**Comment by ermig1979** [comment]
I made my test maximal close to your example (https://github.com/ermig1979/Simd/blob/master/src/Test/TestResize.cpp#L526), but could't reproduce the bug. Could you see at this test and correct me if I did some wrong?

**Comment by ermig1979** [comment]
I think this very specific bug (if it really exists) so I think is better to close this issue.
