### ISSUE TITLE
MEC: Memory-efficient Convolution for Deep Neural Network

### ISSUE THREAD

**Issue by GlebSBrykin** [ermig1979/Simd#208]
Довольно интересная работа по улучшению im2col с целью уменьшения размера буффера: https://arxiv.org/abs/1706.06873 Возможно, будет полезно.

**Comment by ermig1979** [comment]
Спасибо за информацию! К сожалению, она не очень актуальна, так как im2col практически не используется в Simd (используются другие более эффективные методы).
