### ISSUE TITLE
Build number

### ISSUE THREAD

**Issue by mikeversteeg** [ermig1979/Simd#209]
Would it be possible to  increment the build number if there is a new build? This enables me to verify I am running the correct version and it can be used as a reference in Issues (instead of "that release on the morning of April 15h"). 
Thanks.

**Comment by mikeversteeg** [comment]
But `SimdVersion `does not return commit, it returns the version and build number. Which you do not update..

**Comment by ermig1979** [comment]
Its reasonable. I can add commit hash to `SimdVersion`.

**Comment by mikeversteeg** [comment]
Why not use build number? It's standard practice.

**Comment by ermig1979** [comment]
I added git commit ID to SimdVersion.
