### ISSUE TITLE
Different falls when using small scaleFactor

### ISSUE THREAD

**Issue by leugenea** [ermig1979/Simd#21]
Hello.
I experience some strange memory problems when running `Simd::Detection<Simd::Allocator>::Detect` method when cascade was initialized with `scaleFactor = 1.01`. It ends with SIGABRT or SIGBUS.
Compiler is GCC 7.1.1 x86_64, with all extensions. It also reproducible using Visual Studio 2013 (looks like problem is in `Base::DetectionFree`)

**Comment by ermig1979** [comment]
The using so small value of parameter scaleFactor has no practical sense. I think the minimum reasonable value of scaleFactor is equal to 1.05. But of course thank you for bug report. I will try to fix this bug. Could you tell me your size of input image and the values of another parameters. It will be useful in order to reproduce the bug.

**Comment by leugenea** [comment]
Size of input image is 1000×1000. `sizeMin = 40`, `sizeMax = 990`, `roi = View()`, `threadNumber = -1`.
As I can see, I've found problem:
In `InitLevels` there's `_levels.reserve(100)`. When number of levels exceeds 100, reallocation of `_levels` is happened. Struct `Level` doesn't have move constructor/assignment, so it's copied inside of `std::vector::push_back()` and destructor is called on every `Level` object in first buffer. So memory of every handle is freed here: `::SimdDetectionFree(hids[i].handle)`. But everything works fine until next `std::vector` reallocation (in VS 2013 it's happening on size 150). This time destructors for first 100 levels is called again. This leads to double free.

**Comment by ermig1979** [comment]
Thank you. It seems to very close to truth. I will check it tomorrow.

**Comment by leugenea** [comment]
I've noticed one more problem in that place: members of `Level` of type `View` are actually storing the data (i.e. `_owner == true` for this members). This means that in `Level` destructor data from `View`s (like `src`, `roi`, etc.) will be freed too.

**Comment by ermig1979** [comment]
I have fixed this bug. Thank you for your efforts.

**Comment by leugenea** [comment]
Thank _you_ for your fast responses and fix.
