### ISSUE TITLE
YUV420P to YUV422

### ISSUE THREAD

**Issue by mikeversteeg** [ermig1979/Simd#210]
I need to convert planar 420 to interleaved 422 YUV but can't find a function for this, or in fact any efficient way to do this. Did I overlook something?

What I would really need is the opposite of `SimdUyvy422ToYuv420p`: `SimdYuv420pToUyvy422`.

**Comment by mikeversteeg** [comment]
Built, tested and passed with flying colours. Thanks very much for the quick add!

**Comment by ermig1979** [comment]
I added optimizations for all platform (x86, arm).
