### ISSUE TITLE
Failed to compile the FaceDetect example

### ISSUE THREAD

**Issue by mahmoudyassine** [ermig1979/Simd#22]
While trying to compile the example facedetect.cpp i get the following errors:

g++ -std=c++11 face.cpp -I../simd/src
/tmp/ccsGhz9i.o: In function `main':
face.cpp:(.text+0x47c): undefined reference to `SimdAlignment'
face.cpp:(.text+0x4d8): undefined reference to `SimdFree'
face.cpp:(.text+0x63c): undefined reference to `SimdAlign'
face.cpp:(.text+0x678): undefined reference to `SimdAlign'
face.cpp:(.text+0x6c4): undefined reference to `SimdAllocate'
face.cpp:(.text+0x938): undefined reference to `SimdFree'
face.cpp:(.text+0x2cac): undefined reference to `SimdFree'
face.cpp:(.text+0x2d1c): undefined reference to `SimdFree'
face.cpp:(.text+0x2db4): undefined reference to `SimdFree'
/tmp/ccsGhz9i.o: In function `Simd::Detection<Simd::Allocator>::~Detection()':
face.cpp:(.text._ZN4Simd9DetectionINS_9AllocatorEED2Ev[_ZN4Simd9DetectionINS_9AllocatorEED5Ev]+0x38): undefined reference to `SimdDetectionFree'
/tmp/ccsGhz9i.o: In function `Simd::Detection<Simd::Allocator>::Load(std::string const&, int)':
face.cpp:(.text._ZN4Simd9DetectionINS_9AllocatorEE4LoadERKSsi[_ZN4Simd9DetectionINS_9AllocatorEE4LoadERKSsi]+0x28): undefined reference to `SimdDetectionLoadA'
face.cpp:(.text._ZN4Simd9DetectionINS_9AllocatorEE4LoadERKSsi[_ZN4Simd9DetectionINS_9AllocatorEE4LoadERKSsi]+0x78): undefined reference to `SimdDetectionInfo'
/tmp/ccsGhz9i.o: In function `Simd::Detection<Simd::Allocator>::Detect(Simd::View<Simd::Allocator> const&, std::vector<Simd::Detection<Simd::Allocator>::Object, std::allocator<Simd::Detection<Simd::Allocator>::Object> >&, int, double, bool, std::vector<Simd::Rectangle<int>, std::allocator<Simd::Rectangle<int> > > const&)':

Any advice? 
Thanks,
Mark

**Comment by mahmoudyassine** [comment]
this is how the code looks like:

more face.cpp 
#include "Simd/SimdDetection.hpp"
#include "Simd/SimdDrawing.hpp"
int main()
{
    typedef Simd::Detection<Simd::Allocator> Detection;
    Detection::View image;
    image.Load("/home/pi/simd/data/image/face/lena.pgm");
    Detection detection;
    detection.Load("/home/pi/simd/data/cascade/haar_face_0.xml");
    detection.Init(image.Size());
    Detection::Objects objects;
    detection.Detect(image, objects);
    for (size_t i = 0; i < objects.size(); ++i)
        Simd::DrawRectangle(image, objects[i].rect, uint8_t(255));
    image.Save("result.pgm");
    return 0;   
}

**Comment by ermig1979** [comment]
Hello. You can perform next steps:
1. Build Simd Library :
```
    cd ../simd/prj/cmake
    cmake . -DTOOLCHAIN="" -DTARGET=""
    make
```
2. Try to use following compiler options:
```
    g++ -std=c++11 face.cpp -I../simd/src -L../simd/prj/cmake -lSimd
```

**Comment by mahmoudyassine** [comment]
Thanks for the swift reply.
I already Built Simd library as suggested.

using your suggested code, I get diffrent kind of errors now:
g++ -std=c++11 face.cpp -I../simd/src -L../simd/prj/cmake -lSimd
/tmp/cc8CKml6.o: In function `std::thread::thread<std::__future_base::_Async_state_impl<std::_Bind_simple<void Simd::Parallel<Simd::Detection<Simd::Allocator>::Hid::Detect(Simd::View<Simd::Allocator> const&, Simd::Rectangle<int> const&, Simd::View<Simd::Allocator>&, unsigned int, bool)::{lambda(unsigned int, unsigned int, unsigned int)#1}>(unsigned int, unsigned int, Simd::Detection<Simd::Allocator>::Hid::Detect(Simd::View<Simd::Allocator> const&, Simd::Rectangle<int> const&, Simd::View<Simd::Allocator>&, unsigned int, bool)::{lambda(unsigned int, unsigned int, unsigned int)#1} const&, unsigned int, unsigned int)::{lambda()#1} ()>, void>::_Async_state_impl(void Simd::Parallel<Simd::Detection<Simd::Allocator>::Hid::Detect(Simd::View<Simd::Allocator> const&, Simd::Rectangle<int> const&, Simd::View<Simd::Allocator>&, unsigned int, bool)::{lambda(unsigned int, unsigned int, unsigned int)#1}>(unsigned int, unsigned int, Simd::Detection<Simd::Allocator>::Hid::Detect(Simd::View<Simd::Allocator> const&, Simd::Rectangle<int> const&, Simd::View<Simd::Allocator>&, unsigned int, bool)::{lambda(unsigned int, unsigned int, unsigned int)#1} const&, unsigned int, unsigned int)::{lambda()#1}&&)::{lambda()#1}>(Simd::Detection<Simd::Allocator>::Hid::Detect(Simd::View<Simd::Allocator> const&, Simd::Rectangle<int> const&, Simd::View<Simd::Allocator>&, unsigned int, bool)::{lambda(unsigned int, unsigned int, unsigned int)#1}&&)':
face.cpp:(.text._ZNSt6threadC2IZNSt13__future_base17_Async_state_implISt12_Bind_simpleIFZN4Simd8ParallelIZNS4_9DetectionINS4_9AllocatorEE3Hid6DetectERKNS4_4ViewIS7_EERKNS4_9RectangleIiEERSB_jbEUljjjE_EEvjjRKT_jjEUlvE_vEEvEC4EOSP_EUlvE_IEEEOSK_DpOT0_[_ZNSt6threadC5IZNSt13__future_base17_Async_state_implISt12_Bind_simpleIFZN4Simd8ParallelIZNS4_9DetectionINS4_9AllocatorEE3Hid6DetectERKNS4_4ViewIS7_EERKNS4_9RectangleIiEERSB_jbEUljjjE_EEvjjRKT_jjEUlvE_vEEvEC4EOSP_EUlvE_IEEEOSK_DpOT0_]+0xc4): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status

**Comment by ermig1979** [comment]
I forgot to add linker option " -lpthread"

**Comment by mahmoudyassine** [comment]
it worked now after adding  -lpthread to the command. Thanks
