### ISSUE TITLE
Segmentation fault on freeing memory of resized output image after SimdResizerRun for SSE4

### ISSUE THREAD

**Issue by robinvanemden** [ermig1979/Simd#222]
On an Intel Atom processor that support SIMD instruction sets up to and including SSE4.2 I receive a segmentation fault on freeing the pointer to the destination pixels after doing SimdResizerRun():

```
uint8_t* resized_image = malloc(dst_width * dst_c & dst_width * height);
void *resizer = SimdResizerInit(size_width, size_height, dst_width, dst_height, dst_c, SimdResizeChannelByte, SimdResizeMethodNearest);
SimdResizerRun(resizer, src_image_pointer, src_width * dst_c, resized_image, dst_width * dst_c);
SimdRelease(resizer);
free(resized_image)   ---------> Segmentation fault (core dumped)
```

This seems to happen independent of the chosen resize method.

On processors supporting instruction sets up to and including AVX2 I did not encounter this issue.

**Comment by ermig1979** [comment]
Hi! Thank you for bug report. I tried to reproduce it and receive nothing. It works well for SSE4.  Could you give me values of following parameters: size_width, size_height, dst_width, dst_height, dst_c to better bug reproducing?

**Comment by robinvanemden** [comment]
Hi! Thank you for looking into this. I believe the source size was 1920x1080x3, the destination 416x416x3. But I will double check and see if I can generate a minimal example tomorrow!

**Comment by robinvanemden** [comment]
Good morning! I am working on creating a minimal example. I was, however, already able to replicate the segfault within our application on an Intel Atom x5-z8350, with the following sizes:

size_width, size_height, dst_width, dst_height, dst_c:  683, 683, 256, 256, 3

However, when using the following source sizes, there's no segfault:

size_width, size_height, dst_width, dst_height, dst_c:  360, 360, 256, 256, 3

**Comment by robinvanemden** [comment]
I just tested with some isolated replication code, and SIMD ran perfectly for both scenario's on the Atom. So I now suspect there may be some weird issue with our own code here. I'll delve deeper into the issue and keep you posted though!

**Comment by robinvanemden** [comment]
I tried overallocating memory* , which seemed to resolve the segfault on the Atom. However, we then got into issues with Synet functions downstream. Does the SIMD lib (for SSE4) somehow take ownership of the source/dest mem? We did not encounter these issues for AVX or neon on armv7 / aarch64 though. SIMD works like a charm there! But since the SIMD code is now well integrated in our codebase I will remain under the assumption this Atom issue is a weird side-effect that has to do with our own code base**. Should we close this issue for now, as we have yet been unable to generate a clean minimal example that illustrates this issue? 

[* Should we maybe have used SimdAllocate instead of malloc? Still, on neon & avx, we're doing fine with malloc.]

[** We did also encounter a segfault issue with SIMD Base64 (also on AVX) conversion. Could be related? But since back then we switched to https://github.com/aklomp/base64 for Base64 we are now unable to replicate that issue for you too. Again vague & circumstantial on our part, our apologies!]

**Comment by ermig1979** [comment]
Hi! Thank you for so detail bug report. I added checking of buffer overrun and reproduce the bug. Earlier I used for memory allocation function SimdAllocate which add extra memory before and after the array that lead to the hidding of the bug. I try to fix it in the nearest time.

**Comment by robinvanemden** [comment]
Thanks for the update. Great that you have been able to reproduce the bug!

**Comment by ermig1979** [comment]
I found that this bug is actual for SSE41 and AVX2 versions of Resizer. I fixed this bug.

**Comment by robinvanemden** [comment]
We tested today, and Resizer issue is indeed resolved. Thank you!
