### ISSUE TITLE
Feature Request: Bilateral Filter

### ISSUE THREAD

**Issue by PearlDzzz** [ermig1979/Simd#224]
Really enjoy the performance and the library's API,
Would you kindly consider support bilateral filter, which is too slow on CPU.

**Comment by ermig1979** [comment]
Hi! 
I found an example of refernce implementation of bilateral filter:

https://github.com/anlcnydn/bilateral/blob/master/bilateral_filter.cpp

Can I base my implementation on this code or it is better to choose another variants?
If your answer will positive I add this issue to Simd roadmap.

**Comment by PearlDzzz** [comment]
Thanks for your reply.
I think the link above is not a good choice. At present, there are many accelerated versions to refer to, e.g., Recursive Bilateral Filter.
https://github.com/Fig1024/OP_RBF
https://github.com/andyhu-hz/ARBF/blob/cf5c3acd01c50239f5f5d871f1b441d35409d8c8/arbf.cpp

**Comment by ermig1979** [comment]
I added RecursiveBilateralFilter.
