### ISSUE TITLE
How to draw rectangle?

### ISSUE THREAD

**Issue by mikeversteeg** [ermig1979/Simd#229]
I'm trying to draw a rectangle with a linewidth of 2. This works but fills the rectangle:

`SimdFill(pVideo+r.Left+r.Top*iWidth, iWidth, r.Width(), r.Height(), 1, y);
`

so I thought I could skip the area encompassed by the rectangle like this

```
int width = 2;
SimdFillFrame(pVideo+r.Left+r.Top*iWidth, iWidth, r.Width(), r.Height(), 1,
      r.Left+width, r.Top+width, r.Right-width, r.Bottom-width, y);
```

but this gives an AV. Figuring I may have misunderstood the documentation I also tried width=-2 but that also gives an AV. The specified rectangle is well within the bounds of the video frame.

Is this a bug or am I misunderstanding the way this function works?

**Comment by ermig1979** [comment]
See SimdDrawing.hpp

**Comment by mikeversteeg** [comment]
There's no additional information about SimdFill there, only about C++ functions which I do not use.

**Comment by ermig1979** [comment]
Simd implements drawing algorithms only in  SimdDrawing.hpp. This implementation is not optimized and is used for debug purposes.

**Comment by mikeversteeg** [comment]
I know, but I did expect it to work. No problem, I now draw 4 filled rectangles to create the frame.
