### ISSUE TITLE
How to use Simd::Integral with imread image from Opencv

### ISSUE THREAD

**Issue by minhvogremsy** [ermig1979/Simd#231]
Please help me how to read image with opencv and add it to Simd::Integral.
Thanks you!

**Comment by ermig1979** [comment]
There is a simple example:

    #define SIMD_OPENCV_ENABLE
    #include "Simd/SimdLib.hpp"
    typedef Simd::View<Simd::Allocator> View;
    int main()
    {
        cv::Mat cvSrc = imread("image.jpg", IMREAD_GRAYSCALE);
        View simdSrc = cvSrc;
        View simdInt(simdSrc.width + 1, simdSrc.height + 1, View::Int32);
        Simd::Integral(simdSrc, simdInt);
        cv::Mat cvInt = simdInt;
        return 0;
    }

**Comment by minhvogremsy** [comment]
But I have an error Simd/SimdLib.hpp:2392: void Simd::Integral(const Simd::View<A>&, Simd::View<A>&) [with A = Simd::Allocator]: Assertion `src.format == View<A>::Gray8 && sum.format == View<A>::Int32' failed.
Aborted (core dumped)
![olga-kononenko-HkyzJaoJLHw-unsplash](https://user-images.githubusercontent.com/107021576/191227137-713c591c-597a-407b-aa60-c5ce550dc5ea.jpg)

**Comment by ermig1979** [comment]
It seems that function `imread("image.jpg", IMREAD_GRAYSCALE);` reads image in format different from 8-bit gray. 
Perhaps there is need to additional conversion of input image to 8-bit gray because Simd::Integral works only with 8-bit gray input images.
