### ISSUE TITLE
Should _M_ARM64 be also tested for ARM64 definition?

### ISSUE THREAD

**Issue by s-trinh** [ermig1979/Simd#234]
By looking at some Neon code, it looks like `_M_ARM64` is also tested along with `__aarch64__`, see:

https://github.com/libjpeg-turbo/libjpeg-turbo/blob/eb0a024af2d84467b22484a89e98e25b3c38025a/simd/arm/jccolor-neon.c#L56

https://gist.github.com/shibayan/8839930e07898cae4de7be91bff9d5f6#file-libwebp_arm64-patch-L36

https://stackoverflow.com/a/66249936

---

Should this line be updated accordingly?

https://github.com/ermig1979/Simd/blob/74366a147d49a1346019a5ffc89ad14ab1ec42dc/src/Simd/SimdDefs.h#L196

**Comment by ermig1979** [comment]
Hi! This is correct note. Although this macro has to be defined in different [line](https://github.com/ermig1979/Simd/blob/master/src/Simd/SimdDefs.h#L96). I added it (see last commit).

**Comment by s-trinh** [comment]
Thanks :+1:
