### ISSUE TITLE
`SimdRecursiveBilateralFilter` memory leak

### ISSUE THREAD

**Issue by LiuPeiqiHN** [ermig1979/Simd#237]
Code:
```
cv::Mat src = cv::imread("lena.png");

float sigmaSpatial = 0.2;
float sigmaRange = 0.2;

cv::Mat dst(src.size(), src.type());

for (size_t i = 0; i < 10000; i++)
{
	void* filter = SimdRecursiveBilateralFilterInit(src.cols, src.rows, src.channels(), &sigmaSpatial, &sigmaRange, SimdRecursiveBilateralFilterFast);

	if (filter != NULL)
	{
		SimdRecursiveBilateralFilterRun(filter, src.data, src.step1(), dst.data, dst.step1());
		delete filter;
	}
}
```
Memory growth is very fast.

**Comment by ermig1979** [comment]
Hi!

In the description of function [SimdRecursiveBilateralFilterInit](http://ermig1979.github.io/Simd/help/group__recursive__bilateral__filter.html#ga7000a8eba5de2aa5f2f130f08f335e43) there is  
 a note that filter context must be released with using of function [SimdRelease](http://ermig1979.github.io/Simd/help/group__memory.html#ga4e38dedd9f946265c9762858a71aa4cf).

**Comment by LiuPeiqiHN** [comment]
Thank you very much. 

My mistake. I have seen the document, but my eyes didn't notice this. Sorry to bother you.
