### ISSUE TITLE
FaceDetection

### ISSUE THREAD

**Issue by sunjunlishi** [ermig1979/Simd#24]
1 hello  author,I test your FaceDetection example
640*480 image,i use your xml,speed is  6-8ms;
 detection.Init(image.Size(), 1.16, cv::Size(60,60),cv::Size(450,450));
i use my xml ,speed is  1-2ms;
your work is  great,perfect.
2 But, I test my plate detect
 detection.Init(image.Size(), 1.16, cv::Size(60,60),cv::Size(450,450));
speed is  1-2ms
and detection.Init(image.Size(), 1.16, cv::Size(80,20),cv::Size(520,130));
speed is 16-20ms
so  i think that Your algorithm is faster for squares, but rectangles don't support it very well

**Comment by ermig1979** [comment]
Hello. Could you give me size of scan window of cascade that you use to.

**Comment by sunjunlishi** [comment]
Size(64,16) is it?

**Comment by ermig1979** [comment]
And window size of square cascade?

**Comment by szad670401** [comment]
It is exactly that the square window is very fast such as 50*50  。but i use it for some detection such as for pedestrian or license plate ， which windows size is not square （e.g 64*16 ）is not so fast。

**Comment by ermig1979** [comment]
If you use minimal size = cv::Size(60,60) and cascade window size = cv::Size(20,20) then the algorithm can reduce input image in 3 times (from 640x480 to 213x160) and process this small image. In second case the algorithm can reduce image only 1.25 times (relation between minimal size cv::Size(80,20) and cascade window size cv::Size(64,16)). So the algorithm need to process image of 512x384. The relation of areas (512x384)/(213x160) = 5.7. So it is not surprising  that second case is slow.

**Comment by sunjunlishi** [comment]
oh,no.there is a image which  width 640,and height 480.
when detect from minsize(60,60) to maxsize(450,450) time is 7ms;
now dectect from minsize(64,16) to maxsize(520,130) time cost 20ms. why?

**Comment by sunjunlishi** [comment]
i i see,the train size(20,20) and my Size(64,64) is important. is it?

**Comment by ermig1979** [comment]
The algorithm builds pyramid of scaled images with step which is setted by paramemter scaleFactor. Algorithm can skip the level, if window size is lesser or greater then minimal or maximal searched size (scaled to corresponding level). The main time is used to process low levels of the pyramid. So the parameter of minimal object size, cacade window size and scaleFactor  have predominant influence to performance of the algorithm.

**Comment by sunjunlishi** [comment]
oh ,ye scaleFactor 1.2; I understand thoroughly that the road far away is far away . thanks very much.

**Comment by sunjunlishi** [comment]
Both rectangular and square, the speed is 2-3 times higher than the opencv
