### ISSUE TITLE
NEON support

### ISSUE THREAD

**Issue by robinvanemden** [ermig1979/Simd#242]
One of the great features of the SIMD library is its support of both Arm NEON and Intel vector extensions. However, more recent code seems focussed on Intel  SIMD only. Is this by design? Or will NEON versions of newer functions  possibly be added later? That would be awesome.

**Comment by ermig1979** [comment]
Hi! Simd will continue to support ARM NEON. The absent of NEON optimizations of some functions is temporal.

**Comment by robinvanemden** [comment]
@ermig1979 that is terrific, thank you!
