### ISSUE TITLE
Release v5.2.121 MSVS compiler bug error C3861: '_mm_cvtsi64_si128': identifier not found

### ISSUE THREAD

**Issue by Edi61** [ermig1979/Simd#244]
Hello ermig19779,

there is a compiler bug for x86_windows build:
src\Simd\SimdAvx2RecursiveBilateralFilter.cpp(546,49): error C3861: '_mm_cvtsi64_si128': identifier not found [D:\buildtrees\simd\x86-windows-rel\11bec108f0-5ffad3b53a.clean\prj\vs2022\Avx2.vcxproj]
src\Simd\SimdAvx2RecursiveBilateralFilter.cpp(702,49): error C3861: '_mm_cvtsi64_si128': identifier not found [D:\buildtrees\simd\x86-windows-rel\11bec108f0-5ffad3b53a.clean\prj\vs2022\Avx2.vcxproj]

Maybe due to  #ifdef __x86_64__ encapsulation in  emmintrin.h which is only defined for GNU C.

see also:
https://github.com/microsoft/vcpkg/pull/29272

**Comment by ermig1979** [comment]
Thank you for bug report! This error was fixed.
