### ISSUE TITLE
Is SimdConversion.h an offial library header or a candidate?

### ISSUE THREAD

**Issue by Edi61** [ermig1979/Simd#245]
Hi ermig1979
Related to commit https://github.com/ermig1979/Simd/commit/ea3cba8f09002954fdacbce0d0a6db6d94882b57

Currently only /src/Simd/SimdLib.h is referenced.
Shall SimdLib.h be the only .h header file?
Would it be possible to add here somehow SimdConversion.h or make it also part of an official header file?
Or shall these functions maybe replaced and not used from outside?

Ps.: In the project [AntiDupl ](https://github.com/ermig1979/AntiDupl) the functions Square, Min, Max, Base, YuvToBlue, YuvToGreen, YuvToRed,... from SimdConversion.h are used.

Regards,

**Comment by ermig1979** [comment]
I modified AntiDupl to exclude of direct including of file "SimdConversion.h".
