### ISSUE TITLE
Release v5.2.122 MSVS many compiler errors

### ISSUE THREAD

**Issue by Edi61** [ermig1979/Simd#246]
see
[build-x64-windows-rel-out.log](https://github.com/ermig1979/Simd/files/10566141/build-x64-windows-rel-out.log)
x86,x64 windows both not compiling.
see also
https://github.com/microsoft/vcpkg/pull/29272

**Comment by Adela0814** [comment]
Thank you for fixing it so quickly. 

It seems that the problem has not been resolved, this is the latest log.
[build-x86-windows-rel-out.log](https://github.com/ermig1979/Simd/files/10575164/build-x86-windows-rel-out.log)

**Comment by Edi61** [comment]
there is strange behviour, it seems there is a visual dependency?:
- vcpkg build fails, see above
- github build failes also: https://github.com/Edi61/Simd/actions/runs/4072726031/jobs/7015796990
- Appveyor builds ok: https://ci.appveyor.com/project/Edi61/simd
- Local build, seems also ok

**Comment by ermig1979** [comment]
May be because local build use only 64-bit release mode? Now there are errors only in 32-bit release.

**Comment by ermig1979** [comment]
I committed fix.

**Comment by Edi61** [comment]
It's maybe no so important, but Debug Win32 has still errors:
https://github.com/Edi61/Simd/actions/runs/4086426896/jobs/7045697944
https://ci.appveyor.com/project/Edi61/simd/builds/46134371

Ps.:
Did you think about using continous integration per baseline? I don't how you are testing, but it might maybe make life easier and releases would be automatically tested for all configurations? It seems that its also possible to run the tests in parallel.
Since I am myself learning I have just created some example simd workflows from github (but they are limited to 2000h/month):
https://github.com/Edi61/Simd/tree/master/.github/workflows
Alternatively/Additonally use of appveyor is also possible which is only limited to 1 hour compilation time.
After logging in to appveyor website per github and installing appveyor app, it's handled by one configuration file: e.g.
https://github.com/Edi61/Simd/blob/master/appveyor.yml

**Comment by ermig1979** [comment]
I did some fixes for Win32/Debug. Thank you for links!

**Comment by Adela0814** [comment]
I tried the latest commit and it worked. Could you please release the fixes? Thanks.

**Comment by ermig1979** [comment]
Hi! It is good idea but I want to make additional tests on different platforms.

**Comment by Edi61** [comment]
Hi @ermig1979
I have updated appveyor.yml, so that currently all platform combinations are included:
Last build:
https://ci.appveyor.com/project/Edi61/simd/builds/46160236
I can see already some errors:
- [Ubuntu_x86_x64_Release] -> there are test errors,
- [Vs2022_Win32_Debug] -> there are also test errors
- (Not so important: but Visual Arm64 have still errors)
- I am very wondering why are the visual release builds so slow (>1hours), they should be normally faster than debug? And also Cmake Release are much fuster to build? There seem to be some problem which maybe could be optimized.

**Comment by Edi61** [comment]
Latest result looks fine except Visual 2015 and 2017:
https://ci.appveyor.com/project/Edi61/simd/builds/46201864
Are you still planing to support them?

**Comment by ermig1979** [comment]
I will try to fix bugs in old Visual Studios. If it will too difficult I stop support them.
