### ISSUE TITLE
Helper function for cv::invertAffineTransform()

### ISSUE THREAD

**Issue by sbudenkov** [ermig1979/Simd#249]
Hi,
I can't find something like void cv::invertAffineTransform( InputArray M, OutputArray iM ) from OpenCV. It is also possible with cv::WARP_INVERSE_MAP in cv::warpAffine().
Could you please help me with that. I need it for SimdWarpAffineInit().

**Comment by ermig1979** [comment]
http://ermig1979.github.io/Simd/help/group__warp__affine.html#gad69a792126bf952cb14ac3b1c385ece5

**Comment by sbudenkov** [comment]
I see but what about invert? I need inverted matrix.
I can do it using OpenCV but want to do it using Simd.

**Comment by ermig1979** [comment]
I added Simd::InvertAffineTransform().

**Comment by sbudenkov** [comment]
Please close the issue then.
