### ISSUE TITLE
AVX2 Resize assertion

### ISSUE THREAD

**Issue by sbudenkov** [ermig1979/Simd#257]
Hi,

We are observing the following issue.
If create a resizer using bilinear algorithm but for an image where height is 1 an assertion will be raised.
https://github.com/ermig1979/Simd/blob/master/src/Simd/SimdAvx2Resizer.cpp#L38
```cpp
namespace Simd
{
#ifdef SIMD_AVX2_ENABLE 
    namespace Avx2
    {
        void * ResizerInit(size_t srcX, size_t srcY, size_t dstX, size_t dstY, size_t channels, SimdResizeChannelType type, SimdResizeMethodType **method**)
        {
            ResParam param(srcX, srcY, dstX, dstY, channels, type, method, sizeof(__m256i));
            **if (param.IsNearest() && dstX >= F)**
                return new ResizerNearest(param);
```

Nearest Neighbor algorithm will be selected but the method is bilinear was set by user and saved into param structure.

After that an assertion will be raised:
https://github.com/ermig1979/Simd/blob/d2eae69992ef8f2748cd7db4a68cf058f89c1a82/src/Simd/SimdBaseResizerNearest.cpp#L67

**Comment by ermig1979** [comment]
Thank for bug report! I fixed this bug.
