### ISSUE TITLE
ARMv7 linking issue

### ISSUE THREAD

**Issue by robinvanemden** [ermig1979/Simd#263]
Recently, we updated SIMD from v5.2 (December 2022) to the latest release (v5.4.132) for one of our applications. We got the following error when linking the static ARMv7 version of the lib during compilation of the application:

```
sclbl_accelerate.cpp:(.text.startup._GLOBAL__sub_I__Z18importDataToTensorPN11arm_compute6TensorEPf+0x44): undefined reference to `Simd::Neon::GetEnable()'
collect2: error: ld returned 1 exit status
```

Also, the size of the compiled ARMv7 version of the (static) library has gone from 9.8Mb for v5.2 to 3.3Mb for v5.4. The AARCH64 and X64 versions of the library link and compile perfectly fine.

**Comment by ermig1979** [comment]
Hi! The cross platform building of Simd Library for ARM is performed after each commit (see .github/workflows/cmake.yml). And there are no error for last month during this action. I tried to build Simd on ARM manually and it was fine. So I need more info to help you.

P.S. As to reducing of size of Simd Library binaries, I would check SIMD_SYNET cmake parameter. If it is off, the size of library can reduce in several times.

**Comment by robinvanemden** [comment]
Hi! Thank you for your fast response. The building of all architectures we compile the library for (ARMv7, AARCH64, X64) works just fine. It is just when I use the library to compile the final static binary that uses the lib that only the ARMv7 compilation fails with `undefined reference to `Simd::Neon::GetEnable()'`. SIMD_SYNET  is, as it was before, not turned off.

We actually did not change anything in our compilation scripts, we only updated SIMD from 5.2 to 5.4.

The issue only happens for ARMv7. AARCH64 and X64 work perfectly fine. So I thought maybe you would have some suggestion what might cause ARMv7 SIMD 5.2 and 5.4 to behave differently with respect to the thrown  `undefined reference to `Simd::Neon::GetEnable()'`.

I will see if there is some way to circumvent the issue on our side, and keep you posted!

**Comment by robinvanemden** [comment]
Interesting. Two years ago, it seems we had an issue that presented in the same way:

https://github.com/ermig1979/Simd/issues/221

**Comment by robinvanemden** [comment]
If I remove all conditional includes in SimdNeonCpu it all comiles perfectly fine. I will dig a little deeper to see which condition.

**Comment by ermig1979** [comment]
Thank you for so detail bug report. I was able to reproduce the issue. The bug was fixed in last commit. It would be great if you perform independent checking.

**Comment by robinvanemden** [comment]
We tested extensively, and this has resolved our issue. Thanks again!
