### ISSUE TITLE
UYVY422 to YUV420p conversation 

### ISSUE THREAD

**Issue by mikeversteeg** [ermig1979/Simd#267]
I would very much like the function SimdUyvy422ToYuv420p. This will complement the existing SimdYuv420pToUyvy422.

Thanks.

**Comment by ermig1979** [comment]
Hi. I added this issue to roadmap.

**Comment by mikeversteeg** [comment]
Oh, it already exists! I never know where to look in the documentation so I always use Google, and for some reason google cannot find it. Thank you! :)
