### ISSUE TITLE
Console window pops up when using Simd library on Windows in GUI application

### ISSUE THREAD

**Issue by janrysavy** [ermig1979/Simd#268]
When invoking the std::string Execute(const char* cmd) function (during Simd initialization), which internally calls _popen, a console window briefly appears. This behavior is disruptive, especially in GUI application.

**Comment by ermig1979** [comment]
Hi! Thank you for bug report. I added this issue to roadmap.

**Comment by janrysavy** [comment]
Would you be interested in pull request? Use CreateProcess instead of _popen on Windows? Unfortunately it would by more verbose solution.

Lazy loading in this case would be probably also a good idea.

**Comment by ermig1979** [comment]
Hi!
Certainly it will be greate if you make a pull request with solution of this issue. 
I think it will be something based on this:

https://stackoverflow.com/questions/42402673/createprocess-and-capture-stdout

Of course, if it doesn't cause any bothes for you.
