### ISSUE TITLE
Difference between EdgeBackground*() and Background*()

### ISSUE THREAD

**Issue by edward9112** [ermig1979/Simd#271]
Hello,

I am reviewing the list of changes between releases 5* and 6* and I see the removal of EdgeBackground*() functions.
What is the difference between those two (EdgeBackground*() and Background*())?

Thanks,
Ed

**Comment by ermig1979** [comment]
The background model used in Background class uses two bounds of background: lower and upper for every features (grayscale, gradients). The motion must go beyond this bounds to be detected. 
Unlike this EdgeBacground used only one (upper bound).  This method had poorer quality to compare to the first and it was nowhere used last ten years.

**Comment by edward9112** [comment]
Awesome! Thanks mate!
