### ISSUE TITLE
How to use package with cmake ?

### ISSUE THREAD

**Issue by TareHimself** [ermig1979/Simd#276]
How do I include this package into my cmake project ? afteb building no simdConfig.cmake is generated only simdtargets.cmake and `find_package` is looking for a simdConfig.cmake

**Comment by ermig1979** [comment]
Hi! There is [Synet](https://github.com/ermig1979/Synet) project which use Simd as backend. It can be used as an example.

**Comment by TareHimself** [comment]
Thank you,but that project uses `add_subdirectory` , is it not possible to install the project and consume it using `find_package` ? And if not are you open to a PR ?

**Comment by ermig1979** [comment]
There is no such functionality yet. It will be greate if somebody suggest  corresponding pull-request.
