### ISSUE TITLE
Error on compiling windows

### ISSUE THREAD

**Issue by AVConceptProducts** [ermig1979/Simd#28]
Hello,

I'm trying to compile Simd library as static on visual studio 2017.
I get an error :VCEnd exited with code 9009

I uncommented the #define SIMD_STATIC and I selected staticLib on General Configuration. It's for a C++ Project.

I opened the projet from the directory /prj/vs2017w.

Can you please tell me what I did wrong ? Thanks a lot !

**Comment by ermig1979** [comment]
I'm sorry but I can't reproduce the error. I took Visual Studio, selected "Configuration Type" as "Static Library" and project was built without any error. 

P.S. Sometimes Visual Studio return this error. Project reloading helps me.

**Comment by AVConceptProducts** [comment]
Here is the output : 
error MSB3073: The command "C:\Users\fullPath\Simd\prj\vs2017w\\..\cmd\GetVersion.cmd
error MSB3073: :VCEnd" exited with code 9009

Reload means clean ?
Thanks

**Comment by ermig1979** [comment]
Reloading of Visual Studio solution and clean.

**Comment by AVConceptProducts** [comment]
Oh ok I did but still same problem ... 

The problem is here : 
```
<Target Name="PreBuildEvent" Condition="'$(PreBuildEventUseInBuild)'!='false'">
    <Message Text="Description: %(PreBuildEvent.Message)" Condition="'%(PreBuildEvent.Message)' != '' and '%(PreBuildEvent.Command)' != ''"/>
    <Exec Command="%(PreBuildEvent.Command)$(_BuildSuffix)" Condition="'%(PreBuildEvent.Command)' != ''"/>
  </Target>
```
Don't know what to do..

**Comment by AVConceptProducts** [comment]
I tried with VS2015 and I have the same Error.

**Comment by AVConceptProducts** [comment]
Any solution ?
It worked well before when I opened from /prj/vs2017w with vs2017.
I just cloned the last repository and I have this issue.

**Comment by AVConceptProducts** [comment]
I resolved the issue.. By looking to the output I noticed that the script stops when there is a space in the path ... So he does not have access to the .cmd file.

Maybe it could be fixed !
Thanks

**Comment by ermig1979** [comment]
Thank you for bug report. I have fixed this bug.
