### ISSUE TITLE
can't compile with vc2015

### ISSUE THREAD

**Issue by qicosmos** [ermig1979/Simd#3]
hi, this is the error message:
simd\simdavx1ann.cpp(258): error C2719: 'dst': formal parameter with requested alignment of 32 won't be aligned
simd\simdsse1ann.cpp(244): error C2719: 'dst': formal parameter with requested alignment of 16 won't be aligned

**Comment by ermig1979** [comment]
Hello. Thank you for your bug report. I have fixed it.
