### ISSUE TITLE
Clang Errors

### ISSUE THREAD

**Issue by samba3232** [ermig1979/Simd#31]
CLANGCOMPILE : fatal error : error in backend: Cannot select: intrinsic %llvm.arm.neon.vcvtfp2hf;
clang.exe : error : clang frontend command failed with exit code 70 (use -v to see invocation)

**Comment by ermig1979** [comment]
Is this 32-bit or 64-bit?

**Comment by ermig1979** [comment]
Although it is never mind. I have fixed this bug (I hope). Can you check it?

**Comment by samba3232** [comment]
![capture](https://user-images.githubusercontent.com/5028273/33362357-262efe64-d502-11e7-8c0b-e931aed9a49b.PNG)

**Comment by samba3232** [comment]
Again Coming Same Problem....

**Comment by ermig1979** [comment]
Oh! I have fixed this bug for CMake but you used Visual Studio...

**Comment by samba3232** [comment]
Yes..... I am Building For Android That's Why I am using visual studio

**Comment by samba3232** [comment]
I guess that error coming while compiling SimdNeonFloat16.cpp file

**Comment by ermig1979** [comment]
I have done. Could you check again?

**Comment by samba3232** [comment]
Thank you so much its working fine.
