### ISSUE TITLE
Ubuntu14.04 Compilation Error

### ISSUE THREAD

**Issue by ghimiredhikura** [ermig1979/Simd#33]
../../src/Simd/SimdFont.hpp: In member function ‘bool Simd::Font::Draw(Simd::Font::View&, const String&, const Simd::View<Simd::Allocator>::Position&, const Color&, const Color&) const’:
/Simd/prj/cmake/../../src/Simd/SimdFont.hpp:199:13: error: ‘DrawFilledRectangle’ is not a member of ‘Simd’
             Simd::DrawFilledRectangle(region, Rect(region.Size()), background);
             ^
make[2]: *** [CMakeFiles/Test.dir/home/keti/KETI/Simd/src/Test/TestFont.cpp.o] Error 1
make[1]: *** [CMakeFiles/Test.dir/all] Error 2
make: *** [all] Error 2

please let me know how to compile. 

I used these steps to compile as mentioned. 

cd ./prj/cmake
cmake . -DTOOLCHAIN="" -DTARGET=""
make

**Comment by ermig1979** [comment]
Thank you for bug report. This bug has been fixed.
