### ISSUE TITLE
"Try to estimate SVN revision" after taking the project from git

### ISSUE THREAD

**Issue by yurivict** [ermig1979/Simd#34]
It doesn't make sense to expect subversion to be installed, and to display the correct version when the project comes from github.

You should just remove this script, and hardcode the version.

**Comment by ermig1979** [comment]
Simd Library was started as a project on sourceforge.net with using of SVN. Later it was migrated to github.com. But initial project is still supported. Both projects have the same code base. It is main reason why GetVersion.cmd (and GetVersion.sh) script wants to get SVN number in GIT directory.
