### ISSUE TITLE
how to compile the library  by Cmake for  visual studio 2013 or lower version?Thanks

### ISSUE THREAD

**Issue by dreamplayerzhang** [ermig1979/Simd#37]

**Comment by ermig1979** [comment]
I have added project files for Visual Studio 2012/2013.

**Comment by dreamplayerzhang** [comment]
thanks ~ @ermig1979

**Comment by lsy17096535** [comment]
@ermig1979  I fail to build simd on Visual Studio 2013 with Win 10 64bit. 
error log: 错误	1	error C2872: “F”: 不明确的符号	D:\Simd-master\src\Simd\SimdSse2Neural.cpp	155	1	Alg
错误	12	error C2668: “Simd::Avx::Load”: 对重载函数的调用不明确	D:\Simd-master\src\Simd\SimdSse41HogLite.cpp	654	1	Alg

**Comment by ermig1979** [comment]
It seems that I have fixed these errors. But I can't check because I don't have Visual Studio 2013 on my home computer. Could you check it?

**Comment by lsy17096535** [comment]
I have test on vs13.
some error:

错误	13	error C2872: “F”: 不明确的符号	d:\simd-master\src\simd\simdsse2float32.cpp	41	1	Alg

错误	4	error C2780: “void Simd::Sse::Store(float *,__m128)”: 应输入 2 个参数，却提供了 1 个	d:\simd-master\src\simd\simdsse41hoglite.cpp	202	1	Alg


错误	5	error C2664: “__m128 Simd::Sse::Load<true>(const float *)”: 无法将参数 1 从“__m128i *”转换为“const float *”	d:\simd-master\src\simd\simdsse41hoglite.cpp	203	1	Alg

**Comment by ermig1979** [comment]
Fast attempt to fix bug was failed. I am sorry. It is need to wait until next week.

**Comment by lsy17096535** [comment]
@ermig1979  Thanks for your reply. I find some network model use pRelu, do you have any play to provide pRelu function in SIMD?

**Comment by ermig1979** [comment]
I have fixed bugs concerned with Visual Studio 2013. What about PRelu I have plan to create another DNN framework. Possible this issue will be implemented there.

P.S. It will be better if you create separate issue about PRelu.
