### ISSUE TITLE
Performance degrade of "Simd::Detection" as compared to OpenCV "CascadeClassifier". 

### ISSUE THREAD

**Issue by ghimiredhikura** [ermig1979/Simd#38]
Dear Sir, 

I am experiencing low detection rate of Simd::Detection as compared to opencv CascadeClassifier using Haar features. I believe they are same function. Am I missing something? please help. 

Best,
Deepak
South Korea

**Comment by ermig1979** [comment]
The algorithm of Haar cascade classification implemented in Simd Library is very close to original algorithm in OpenCV. But they are not fully equal. Nevertheless the accuracy of Simd implementation must not be strongly different from originals. It would be better if you give me your cascade and image in order I can perform debug.
