### ISSUE TITLE
How to build on Ubuntu 14.04?

### ISSUE THREAD

**Issue by houzy** [ermig1979/Simd#4]
What I have done:
      1: cd build
      2: cmake ../prj/cmake
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMAKE_BUILD_TYPE variable is not defined. Set CMAKE_BUILD_TYPE = 'Release'.
Using crossplatform toolchain '' for '' platform.
CMAKE_SYSTEM_PROCESSOR = 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/houzy/Simd/build
      3: make (No output)
What is the correct way to build this repo? Thanks.

**Comment by ermig1979** [comment]
Hello. Have you read this manual http://simd.sourceforge.net/help/group__simd__overview.html ?

**Comment by houzy** [comment]
Oh, it's my fault, I haven't read it. Thanks for your help.@ermig1979

**Comment by ermig1979** [comment]
What is your platform?
Try to perform the command:
cmake . -DTOOLCHAIN="" -DTARGET=""

**Comment by houzy** [comment]
Yes, it works! But I get another error.
1: cd prj/cmake
2: cmake . -DTOOLCHAIN="" -DTARGET=""
Outputs:
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMAKE_BUILD_TYPE variable is not defined. Set CMAKE_BUILD_TYPE = 'Release'.
CMAKE_SYSTEM_PROCESSOR = x86_64
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    TARGET


-- Build files have been written to: /home/houzy/Simd/prj/cmake
3: make
I got an error:
[ 80%] Linking CXX static library libSimdAvx2.a
[ 80%] Built target SimdAvx2
Scanning dependencies of target Simd
[ 80%] Building CXX object CMakeFiles/Simd.dir/home/houzy/Simd/src/Simd/SimdLib.cpp.o
/home/houzy/Simd/src/Simd/SimdLib.cpp:51:30: fatal error: Simd/SimdVersion.h: No such file or directory
 #include "Simd/SimdVersion.h"
                              ^
compilation terminated.
make[2]: *** [CMakeFiles/Simd.dir/home/houzy/Simd/src/Simd/SimdLib.cpp.o] Error 1
make[1]: *** [CMakeFiles/Simd.dir/all] Error 2
make: *** [all] Error 2

**Comment by ermig1979** [comment]
I have fixed this error. Could you check it at your platform?

**Comment by houzy** [comment]
Yes, it works now. No error and warning.
