### ISSUE TITLE
assert(0) in View = operator

### ISSUE THREAD

**Issue by teor292** [ermig1979/Simd#41]
Hi. There is = operator in View class, and I think there is a bug with assert:
` template <template<class> class A> SIMD_INLINE View<A> & View<A>::operator = (const View<A> & view)`
`    {`
 `       if (this != &view)`
   `     {`
     `       if (_owner && data)`
     `       {`
    `            Allocator::Free(data);`
    `            assert(0); // <= here, it's stop application`
   `         }`
 `       .....`
 `   }`

**Comment by ermig1979** [comment]
It is not a bug. It is a feature. View type has copy operator and copy constructor, but they only create a reference to the original View (for performance reasons). To perform deep copy use Simd::Copy or View::Clone. This assert is used to prevent attempt to perform deep copy with using of copy operator.

**Comment by teor292** [comment]
But in some cases I don't need a deep copy, but only a reference. For example: the function receives an image (view) as a parameter; creates an image (img) of bgr24 type; after check type of view image and convert to bgr24. If view is bgr24, so `img = view`, and after there is some processing. 
Of course, I can create img in every `if` and `else if`, but in my case it does not make sense.
However, if we consider this assert as a defense against inattention of 'not copy', then everything is ok.

**Comment by ermig1979** [comment]
Maybe I am not right. Could you give me your code as example?

**Comment by teor292** [comment]
`Simd::View<Simd::Allocator> img(view.width, view.height, Simd::View<Simd::Allocator>::Bgr24); `
`if (view.format == Simd::View<Simd::Allocator>::Format::Gray8)`
`{`
` SimdGrayToBgr(view.data, view.width, view.height, view.stride, img.data, img.stride);`
`}`
`else if (view.format == Simd::View<Simd::Allocator>::Format::Bgra32)`
`{`
`SimdBgraToBgr(view.data, view.width, view.height, view.stride, img.data, img.stride);`
`}`
`else if (view.format == Simd::View<Simd::Allocator>::Format::Bgr24)`
`{`
`img = view;`
`}`

After that I copy img to Bitmap object (.Net).

**Comment by ermig1979** [comment]
I would recomend to use function Simd::Convert():

    typedef Simd::View<Simd::Allocator> View;
    View img;
    if(view.format != View::Bgr24)
    {
        img.Recreate(view.Size(), View::Bgr24);
        Simd::Convert(view, img);
    }
    else
        img = view;

**Comment by teor292** [comment]
Thanks, it's much better than done by me :+1:
