### ISSUE TITLE
Crash in AddConvolution

### ISSUE THREAD

**Issue by christ115** [ermig1979/Simd#42]
When do convolution on a very small image (e.g., 2x2) by using "SimdNeuralConvolutionForward", the following function will crash due to out-of-range memory access.

template <bool align, size_t kernelX, size_t kernelY> void AddConvolution(const float * src, size_t srcWidth, size_t srcHeight, size_t srcDepth, const float * weight, float * dst, size_t dstWidth, size_t dstHeight, size_t dstDepth)

The possible reason may be "col" < 0 and then "pdst + col" point to an illegal area. Could you give some suggestions?

if (dstWidth - alignedWidth) {
        size_t col = dstWidth - F;
        __m128 _dst = Load<false>(pdst + col);
        _dst = _mm_add_ps(_dst, _mm_and_ps(tailMask, Convolution<kernelX, kernelY>::template Forward<false>(psrc + col, srcWidth, _weight)));
       Store<false>(pdst + col, _dst);
}

**Comment by ermig1979** [comment]
Thank you for bug report. I will try to fix this bug.

**Comment by ermig1979** [comment]
I have added a check for minimum image width. Is the crash still here?

**Comment by christ115** [comment]
It works well now. Thanks for your quick response.
