### ISSUE TITLE
ResizeBilinearGray for NEON

### ISSUE THREAD

**Issue by teor292** [ermig1979/Simd#43]
Hi! There are ResizeBilinearGray optimization functions for SSSE3, AVX2 and AVX512, but not for NEON. So, I created such function for NEON and test it, but separately from Simd (unfortunately, I do not have the opportunity to test it together with the library on the ARM now). It seems like it works. Please, test it and add to repo.
[SimdNeonResizeBilinear.txt](https://github.com/ermig1979/Simd/files/1702522/SimdNeonResizeBilinear.txt)

**Comment by teor292** [comment]
Oh sorry, it works not for all sizes -_-

**Comment by ermig1979** [comment]
Hello. You forgot to update Copyrights.

**Comment by teor292** [comment]
Ok. 
[SimdNeonResizeBilinear.txt](https://github.com/ermig1979/Simd/files/1702956/SimdNeonResizeBilinear.txt)

**Comment by ermig1979** [comment]
I have added your changes. Please check their.

**Comment by teor292** [comment]
Ok, thanks.
