### ISSUE TITLE
Face Tracking (not detection)

### ISSUE THREAD

**Issue by samba3232** [ermig1979/Simd#45]
Face Detection:
Simd::detection  class fine but
Face Tracking:
?

**Comment by ermig1979** [comment]
Good face tracker have to be based on face recognition. It is not easy task.

**Comment by samba3232** [comment]
At least Is there any methods for to get landmarks?

**Comment by ermig1979** [comment]
Lately I develop a [project](https://github.com/ermig1979/Synet) to fast inference of previously trained neural models. It is something like Inference Engine but it also supports ARM CPU. May be it will be useful for you. Test examples contain models trained for face detection and face landmarks detection (some of landmarks are correspond to eyes).
