### ISSUE TITLE
internal compiler error: in subreg_get_info while compiling on Raspbian

### ISSUE THREAD

**Issue by mahmoudyassine** [ermig1979/Simd#48]
[ 41%] Building CXX object CMakeFiles/Simd.dir/home/pi/simd/src/Simd/SimdNeonBgrToBgra.cpp.o
/home/pi/simd/src/Simd/SimdNeonBgrToBgra.cpp: In function ‘void Simd::Neon::BgrToBgra(const uint8_t*, size_t, size_t, size_t, uint8_t*, size_t, uint8_t)’:
/home/pi/simd/src/Simd/SimdNeonBgrToBgra.cpp:69:9: internal compiler error: in subreg_get_info, at rtlanal.c:3679
         }
         ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
CMakeFiles/Simd.dir/build.make:1766: recipe for target 'CMakeFiles/Simd.dir/home/pi/simd/src/Simd/SimdNeonBgrToBgra.cpp.o' failed
make[2]: *** [CMakeFiles/Simd.dir/home/pi/simd/src/Simd/SimdNeonBgrToBgra.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/Simd.dir/all' failed
make[1]: *** [CMakeFiles/Simd.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Any idea how to solve that? I'm using latest Raspbian Stretch Lite and new Raspberry-Pi 3 B Plus.

Thanks,

**Comment by mahmoudyassine** [comment]
used cmake command:
 cmake . -DTOOLCHAIN="/usr/bin/arm-linux-gnueabihf-g++" -DTARGET="arm" -DCMAKE_BUILD_TYPE="Release"
Build type: Release
Target: arm
Library: STATIC
Toolchain: /usr/bin/arm-linux-gnueabihf-g++
ID: GNU
Version: 6.3.0

**Comment by ermig1979** [comment]
I have no idea about why this error is occured. In Monday I will try to reproduce this bug.

**Comment by eymengunay** [comment]
Hello @mahmoudyassine ,

Could you find a solution to this problem? I'm having the same issue on my installation of Raspbian Stretch with Raspberry PI 3 B.

**Comment by seovchinnikov** [comment]
got this too...
without body of this function compilation was finished ok

**Comment by ermig1979** [comment]
The bug was reproduced and fixed.
