### ISSUE TITLE
Avx perfomance degradation compared to SSE

### ISSUE THREAD

**Issue by teor292** [ermig1979/Simd#49]
Hi. I test some neural network with AVX2, AVX and SSE instructions and found that AVX is less perfomance than even SSE. I think this is a problem or maybe AVX is meaningless for neural network (or my type of neural network).

**Comment by ermig1979** [comment]
Hi. Could you to let know your info about your CPU ?

**Comment by teor292** [comment]
I test it on two cpu: Intel Core I5-2500k and Intel Xeon CPU E3-1225 V3

**Comment by ermig1979** [comment]
Is the performance decreasing strong?
If it is about 98-102% - then it is a measure error. Some of neural functions are limited by bandwidth of memory. So performance boosting is achieved when you use small image size which can be placed in CPU cache. In test framework try to use parameters -w=640 -h =480 instead default values -w=1920 -h=1080.

**Comment by teor292** [comment]
It is not strong, but AVX has 256 bit and SSE 128 bit, so I think it must be faster, not slower in any case. I test it not on test framework, but with my test program. For first image SSE give me 0.45 ms time and AVX 0.55 ms (on I5), for the second image (neural was the same, but with different input size of image) AVX 1.43 ms and SSE 1.38 ms (on Xeon). Of cource I can disable AVX, but I think that such results are strange.

**Comment by ermig1979** [comment]
What is the function?

**Comment by ermig1979** [comment]
What is the function?

**Comment by teor292** [comment]
[NeuralSimple.txt](https://github.com/ermig1979/Simd/files/1825093/NeuralSimple.txt)
Here is simplify test function and neural architecture. It get 0.278 ms for AVX and 0.266 for SSE (and AVX2 get the same result as SSE).

**Comment by ermig1979** [comment]
Neural is depricated now. Use [Synet](https://github.com/ermig1979/Synet).
