### ISSUE TITLE
aarch64 is not support NEON

### ISSUE THREAD

**Issue by pch1603** [ermig1979/Simd#54]
Build type: Release
Target: aarch64
Library: STATIC
Toolchain: /usr/bin/c++
ID: GNU
Version: 5.4.0
Try to estimate SVN revision:
Subversion is not installed!
Last project version '4.1.64' is equal to current version '4.1.64'.
File '../../src/Simd/SimdVersion.h' is already exist.
Skip updating of '../../src/Simd/SimdVersion.h' file.
-- Configuring done
-- Generating done

I use haar cascade detection for simd, a times slower than the speed of opencv.

CmakeList.txt exist this:
```
elseif((CMAKE_SYSTEM_PROCESSOR MATCHES "arm") OR (CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64"))

    if(CMAKE_SYSTEM_PROCESSOR MATCHES "arm")
        set(CXX_NEON_FLAG "-mfpu=neon -mfpu=neon-fp16 -mfp16-format=ieee")
    else()
        set(CXX_NEON_FLAG "")
    endif()
```

**Comment by ermig1979** [comment]
Thank you for bug report. I will check it when I have access to any device with ARM-64.

**Comment by ermig1979** [comment]
Arm64 is used NEON by default. This compiler option is not need.
