### ISSUE TITLE
Tree-based cascades for simd::Detection

### ISSUE THREAD

**Issue by AdrianEddy** [ermig1979/Simd#55]
Is there any chance to see support for tree-based cascades in simd::Detection?

**Comment by ermig1979** [comment]
Are the tree-based cascades often used?

**Comment by AdrianEddy** [comment]
I don't know if they are often used in general, but the "classifier_frontalface_alt2.xml" from OpenCV is a popular choice and it's tree-based

**Comment by ermig1979** [comment]
I remember that I didn't find any methods to vectorize tree-based cascade when I was implementing Simd::Detection. I will try again but I do not sure that I will can do it.

**Comment by ermig1979** [comment]
Lately I develop a [project](https://github.com/ermig1979/Synet) to fast inference of previously trained neural models. It is something like Inference Engine but it also supports ARM CPU. May be it will be useful for you.
