### ISSUE TITLE
MinGW64 compatibility

### ISSUE THREAD

**Issue by SairesArt** [ermig1979/Simd#59]
Trying to build with GCC for Windows (MinGW64) via cmake makes cmake quit due to unknown Plattform (Platform/MINGW64_NT-10.0).
This is my toolchain of choise. Would it be possible to get it running?
[CopyOfCMakeCache.txt](https://github.com/ermig1979/Simd/files/2119918/CopyOfCMakeCache.txt)

**Comment by ermig1979** [comment]
I have fixed this bug. Now you can build the library with using of MinGW:

    cd .\prj\cmake
    cmake . -DTOOLCHAIN="your_toolchain\bin\g++" -DTARGET="x86_64" -DCMAKE_BUILD_TYPE="Release" -DLIBRARY="STATIC" -G "MinGW Makefiles"
    mingw32-make

**Comment by SairesArt** [comment]
Thanks for the super quick response.
After cloning a new repo it errors out with: "CMake Error: Could not create named generator MinGW Makefiles"
I input the toolchain in different ways, different ways to write the path, too. Am I doing something wrong?
I'm on MSYS2 in case that matters.

**Comment by ermig1979** [comment]
You have to add MinGW  to PATH.

**Comment by SairesArt** [comment]
MSYS2 installer does that already automatically. I can type g++ in Windows's cmd and it returns the expected gcc compiler, incase that's what you mean.

**Comment by ermig1979** [comment]
I perform next steps:

    cd prj/cmake
    mkdir build
    cd build
    cmake .. -DTOOLCHAIN="C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin\g++" -DTARGET="x86_64" -DCMAKE_BUILD_TYPE="Release" -DLIBRARY="STATIC" -G "MinGW Makefiles"
    mingw32-make -j8

**Comment by SairesArt** [comment]
MSYS2's cmake Errors out with this nothing telling 

> "CMake Error: Could not create named generator MinGW Makefiles"

Just to make sure, I also downloaded cmake for Windows independent of MSYS2's environment. That errors out with:

> "The current CMakeCache.txt directory C:/vladsIDE/MSYS2/home/Bonfire/Simd/prj/cmake/CMakeCache.txt is different than the directory /home/USERNAME/Simd/prj/cmake where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt"

**Comment by ermig1979** [comment]
I would recommend to delete cached files before building.

**Comment by SairesArt** [comment]
I deleted all cache files, tried with cmake gui and non gui. Nothing seems to work.
Command line always gives the same error as above.

Skipping MSYS and doing stuff myself over cmake gui gives.
"Try to estimate SVN revision: Execution file "SubWCRev.exe" is not found!"
Followed by 
"CMake Error at CMakeLists.txt:222 (message):
  Unknown value of CMAKE_SYSTEM_PROCESSOR!"

**Comment by SairesArt** [comment]
@ermig1979 
Ok I figured it out - somewhat
MSYS confuses cmake because it tells it is a MINGW64_NT-10.0 Plattform.
Calling mingw64's cmake from Windows's console Enviroment doesn't work. It spits out no Error message, just "CMake Error: Could not create named generator MinGW Makefiles"

Calling the **Windows Cmake** from the **Windows's Console** stops cmake being so hopelessly confused. This finishes generating makefiles. The Makefiles are not for MSYS and will not work in that enviroment. Cmake has an extra function for MSYS makefiles, but it is undefined in SIMD.

Now calling mingw32-make works. The Test.exe immediately crashes though. Still gotta check whether the library itself works.
