### ISSUE TITLE
Cmake fails with SimdVersion.h

### ISSUE THREAD

**Issue by SairesArt** [ermig1979/Simd#60]
After fighting through making cmake work on MinGw, I gradually come to understand how this all works, with this thread being the golden helper: https://github.com/glfw/glfw/issues/843#issuecomment-250316815

Whilst I can compile without MSYS only using the stock MinGW install, I'm interested in getting it to work with "Msys Makefiles" or "Unix Makefiles"
I always end up with:
`Skip updating of file ""C:/Users/Bonfire/Desktop/winVAI/Projects/suite/pkg/Simd/prj/cmake/../..\src\Simd\SimdVersion.h"" because there are not any changes.`

Everything else seems to work, make -j8 posts many compiled files, but it always files at this one:
`/SimdLib.cpp: In function 'const char* SimdVersion()':
C:/Users/Bonfire/Desktop/winVAI/Projects/suite/pkg/Simd/src/Simd/SimdLib.cpp:79:12: error: 'SIMD_VERSION' was not declared in this scope
     return SIMD_VERSION;
            ^~~~~~~~~~~~`

Is there a way to fix this?

**Comment by SairesArt** [comment]
@ermig1979 
With
`cmake . -DTOOLCHAIN="g++" -DTARGET="x86_64" -DCMAKE_BUILD_TYPE="Release" -DLIBRARY="STATIC" -G "MSYS Makefiles"`
I get the attached log.txt as output. [log.txt](https://github.com/ermig1979/Simd/files/2261978/log.txt)

The original SimdVersion.h.txt is from the github clone.
After running cmake a SimdVersion.h is created under Simd\src\Simd.
But the file is 0bytes and completly empty.

**Comment by ermig1979** [comment]
I would recommend to delete SimdVersion.h file and try again.

**Comment by SairesArt** [comment]
@ermig1979 
As expected, deleting SimdVersion.h:
After cmake before make: "fatal error: Simd/SimdVersion.h: No such file or directory"

After Cmake, before a second cmake:
it just recreates the same empty SimdVersion.h and make errors out with " error: 'SIMD_VERSION' was not declared in this scope"

**Comment by ermig1979** [comment]
I have added possibility to build project without generation of SimdVersion.h :

    cmake . -DTOOLCHAIN="g++" -DTARGET="x86_64" -DCMAKE_BUILD_TYPE="Release" -DLIBRARY="STATIC" -G "MSYS Makefiles" -DCHECK_VERSION=0

**Comment by SairesArt** [comment]
@ermig1979 
Thanks for that. It compiles now, but fails further on. I have a hunch why though, cmake may be confused on the Static option! I hope I'm not killing your nerves :]
The compile finishes without error, but the Test application doesn't run (exits with Illegal instruction) and compiling
`#include Simd/SimdLib.h"`
`int main() {`
`info = SimdCpuInfo();`
`return 0;`
`}`
Errors out with "undefined reference to `__imp_SimdCpuInfo"
__imp usually refers to linking .dlls, but I built Simd statically and correctly linked libSimd.a

**Comment by ermig1979** [comment]
I would see your compiler and linker options in order to reproduce the error.

**Comment by SairesArt** [comment]
Linker and compiler options are identical.
This is the full command: ../../MSYS/mingw64/bin/gcc -Ilib/Simd/src -static bin/obj/main.o -o bin/debug/main -Llib/Simd/prj/cmake -lSimd
The compiler never finishes, so it doesn't even start the linker.

With -flto the linker get's involved and pukes out a long list of undefined references.
`ld.exe: lib/Simd/prj/cmake\libSimd.a(SimdAvx2YuvToHue.cpp.obj):SimdAvx2YuvToHue.cpp:(.text.startup+0xc): undefined reference to `std::ios_base::Init::Init()' collect2.exe: error: ld returned 1 exit status`

**Comment by ermig1979** [comment]
You have to add macro SIMD_STATIC before include Simd API:

    #define SIMD_STATIC
    #include "Simd/SimdLib.h"
    int main()
    {
        int info = SimdCpuInfo();
        return 0;
     }

**Comment by SairesArt** [comment]
@ermig1979 
Ok, great! Works all fine now. Thanks! Skipped that part when reading the doc...
I had to switch to g++ instead of gcc, otherwise compilation fails with .cpp files.

Just as a side question. The documentation mentioned "The Simd Library has C API ". Does that mean I still have to compile with g++? Because with g++ all .c files are treated as cpp files, as I understand it.

**Comment by ermig1979** [comment]
You can use Simd in C code (main.c):

    #define SIMD_STATIC
    #include "Simd/SimdLib.h"
    int main()
    {
        int info = SimdCpuInfo();
        return 0;
    }

Options to compile it (I built the library in prj/cmake/build):

    gcc main.c -o main -I../../../src/ -L./ -lSimd -lpthread -lstdc++ -lm

**Comment by SairesArt** [comment]
Ok, so I was correct, linking against stdc++ is needed. Many thanks for everything!
