### ISSUE TITLE
Multiple definition of Average16

### ISSUE THREAD

**Issue by ElimsSmile** [ermig1979/Simd#61]
Hello! 
There is a problem in Visual Studio 2013 with release configuration: the function Simd::Avx2::Average16 is defined twice (in SimdMath.h and in SimdAvx2ReduceGray2x2.cpp), because SIMD_MADDUBS_ERROR is defined.

Error from MSVS build output: 
```
1>..\..\src\Simd\SimdAvx2ReduceGray2x2.cpp(34): error C2084: function '__m256i Simd::Avx2::Average16(const __m256i &,const __m256i &,const __m256i &,const __m256i &)' already has a body
1>          D:\Test\Simd-master\src\Simd/SimdMath.h(781) : see previous definition of 'Average16'
```

**Comment by ermig1979** [comment]
Thank you for bug report. The bug has been fixed.
