### ISSUE TITLE
Build error with -DCMAKE_BUILD_TYPE="Debug"

### ISSUE THREAD

**Issue by ElimsSmile** [ermig1979/Simd#65]
Hello.
Build with GCC 5.4.0 fails with the next errors:
![image](https://user-images.githubusercontent.com/4352191/44078756-03cd8d58-9fb0-11e8-9a16-ffa7f65a4403.png)

**Comment by ermig1979** [comment]
I use GCC 5.5.0 and the build is performed without any errors:

    cd simd/prj/cmake
    mkdir build
    cd build
    cmake .. -DTOOLCHAIN="g++-5" -DTARGET="" -DCMAKE_BUILD_TYPE="Debug"
    make -j8

It is possible that  GCC 5.4.0 does not support AVX-512. I would recommend to use option -DAVX512=0 in order to build Simd.

**Comment by ElimsSmile** [comment]
But with release build type there are no such errors
