### ISSUE TITLE
_mm256_fmadd_ps prompt Illegal Construction

### ISSUE THREAD

**Issue by w136111526** [ermig1979/Simd#67]
In the win 7x64-bit operating system environment, I used Visual Studio 2015 to call the AVX2 function _ mm256_fmadd_ps method and also defined / arch: AVX2, but it prompted Illegal Construction. How do I fix this problem?
 my code as following:
       __declspec(align(32)) float  f[32] = { 1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0 };
	__declspec(align(32)) float f1[32] = { 2.0,4.0,6.0,8.0, 10.0, 12.0,14.0,16.0 };
	__declspec(align(32)) float f2[32] = { 0 };
	__m256 sum_vec = _mm256_setzero_ps();
	__m256 fl0 = _mm256_load_ps(f);
	__m256 fl1 = _mm256_load_ps(f1);
	__m256 sf2 = _mm256_fmadd_ps(fl0, fl1, sum_vec);
	_mm256_store_ps(f2, sf2);

**Comment by ermig1979** [comment]
Hello.

Does your CPU support AVX2 and FMA extensions?

https://github.com/ermig1979/Simd/blob/master/src/Simd/SimdEnable.h

**Comment by w136111526** [comment]
My computer does not support the _mm256_fmadd_ps AVX2 command. can I use 
_ mm256_add_ps(__mm2566_mul(A, B), C) instead of _ mmm256_fmadd_ps(A, B, C)?

**Comment by ermig1979** [comment]
yes of course
