### ISSUE TITLE
make failed with the simd/prj/vs2017a

### ISSUE THREAD

**Issue by galileolvpo** [ermig1979/Simd#69]
some errors in the picture 
![err1](https://user-images.githubusercontent.com/18024983/44695624-9dc1ad00-aa63-11e8-9752-69d0c259855c.png)
![err2](https://user-images.githubusercontent.com/18024983/44695634-a31ef780-aa63-11e8-8879-0c15bcc5144e.png)

**Comment by ermig1979** [comment]
Thank you for bug report. I have fixed this bug.
