### ISSUE TITLE
Undefined reference to symbol 'pthread_create@@GLIBC_2.4'

### ISSUE THREAD

**Issue by zanazakaryaie** [ermig1979/Simd#74]
Hello

I've just installed the library on Raspbian Jessie.
I tried to compile the UseFaceDetection.cpp in /Simd/src/Use but it gives me:
`Undefined reference to symbol 'pthread_create@@GLIBC_2.4'`

I added `-pthread` to my compiler flags but It reproduced the error. What I should I do?

**Comment by ermig1979** [comment]
I think that you need to add linker option -lpthread.

**Comment by zanazakaryaie** [comment]
Thanks for your reply
I also added `-lpthread` but the same error happens

**Comment by ermig1979** [comment]
Try to add  `-pthread`.

**Comment by zanazakaryaie** [comment]
Hi,

It was a simple mistake. I was adding -lpthread to compiler options in my IDE while I had to add it to the linker options. 

The code is now running. But the speed is shockingly fast! OpenCV runs and LBP Cascade at 40 FPS while SIMD runs it at 250-300 FPS! 

Could you please introduce a reference to learn NEON? I couldn't find a good book or course.

**Comment by ermig1979** [comment]
To learn NEON I use official docs: http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0472j/chr1360928373893.html

**Comment by zanazakaryaie** [comment]
Thanks sir
