### ISSUE TITLE
char* add error  Issues

### ISSUE THREAD

**Issue by w136111526** [ermig1979/Simd#75]
Hello, I want to use SSE for 8-bit char array operation, but the result is not correct, how can I modify it, my code is as follows：
char  data[32] = { -21, -22, 13, 124, 5, -67, 8, -38, 0, 14, 21, 50, 04, 22, 6,  43, 4,  2,  84, 94, 2, 4, 11, 29, 41, 24,4,2,22,12,97 };
char  data1[32] = { 121, 22, -33, -124, 15, -67, 8, -38, 0, 14, 21, 50, 04, 22, 6,  43, 4,  2,  84, 94, 2, 4, 11, 29, 41, 24,4,2,22,12,97 };
	__m128i FirstP0 = _mm_unpacklo_epi8(_mm_loadl_epi64((__m128i *)data), Zero);
	__m128i FirstP1 = _mm_unpacklo_epi8(_mm_loadl_epi64((__m128i *)data1), Zero);
	__m128i FirstAdd = _mm_add_epi16(FirstP0, FirstP1);
	__m128i pkAdd8 = _mm_packus_epi16(FirstAdd, Zero);
	_mm_store_si128((__m128i*)dAddSum, pkAdd8);
	nTime++;
	for (int i = 0; i < 8; i++)
		cout << (int)dAddSum[i] << endl;

**Comment by ermig1979** [comment]
I don't know exactly, but the using of intrinsic  _mm_packus_epi16 is looked strange (it packs int16_t to uint8_t ). Try to use _mm_packs_epi16.

**Comment by w136111526** [comment]
The result is still wrong. I need to do dot operations with the int8 vector. The length is 128 bits. If the int8 can not be used, will the conversion to the short operation be inefficient?

**Comment by ermig1979** [comment]
It will be better if you get me an example of your scalar code. And I could get you the best way to optimize it with using of SSE.

**Comment by w136111526** [comment]
My code as following，nDim=128, This function works very fast, but I need to perform 1000 * 10000 such comparisons. The template contains negative values and must be calculated using char.

template<int nDim>
float CompareTemplate(const BYTE * pbyTemplate1, const BYTE * pbyTemplate2)
{
	int dot = 0;
	float mod[2] = { 0， 0};
	memcpy(&mod[0], pbyTemplate1, sizeof(float));
	memcpy(&mod[0], pbyTemplate2, sizeof(float));
	char* p1 = (char*)(pbyTemplate1 + sizeof(float));
	char* p2 = (char*)(pbyTemplate2 + sizeof(float));
	for (int i = 0; i < nDim; ++i)
		dot += p1[i] * p2[i];
	float fScore = (1 + static_cast<float>(dot * mod[0] * mod[1])) * 0.5;
}

**Comment by ermig1979** [comment]
1) Use _mm_cvtepi8_epi16 instead of _mm_unpacklo_epi8 to convert int8_t to int16_t (it from SSE4.1).
2) Use _mm_madd_epi16 and _mm_add_epi32 to accumulate result dot product sum.

The nearest analogue in Simd - CorrelationSum.
https://github.com/ermig1979/Simd/blob/master/src/Simd/SimdSse2Statistic.cpp

**Comment by w136111526** [comment]
Thank you. I've solved this problem many times faster.

**Comment by ermig1979** [comment]
I was glad to help you.
