### ISSUE TITLE
cross-compile using cmake

### ISSUE THREAD

**Issue by meloncolie** [ermig1979/Simd#77]
Hello, i have problem with cross-compiling.
if i make a subdirectory and call `cmake ..` in it, no CMakeFiles, CMakeCache and related files will be generate. Here is the commands:
```
mkdir build-arm-linux-gnueabihf && cd build-arm-linux-gnueabihf
cmake .. -DTOOLCHAIN="/usr/bin/arm-linux-gnueabihf-g++" -DTARGET="arm" -D
CMAKE_BUILD_TYPE="Release" -DLIBRARY="STATIC"
```
This phenomena is pretty wired in my respect, i am wandering how this happens and how could i make it in a subdirectory. Thanks a lot

**Comment by ermig1979** [comment]
I have performed the commands above and they are work fine.
