### ISSUE TITLE
ndk version

### ISSUE THREAD

**Issue by galileolvpo** [ermig1979/Simd#78]
which ndk version do the vs2017a use?
I have some errs when I build the prj

**Comment by ermig1979** [comment]
MSVC 14.14.26412 (2017 preview)
MSVC 14.20.27027 (2019 preview)

**Comment by galileolvpo** [comment]
thx, I would also like to know the androidNdk version, 
now I am using W:\Microsoft\AndroidNDK64\android-ndk-r15c\
but it was something wrong

**Comment by ermig1979** [comment]
I use android-ndk-r15c.
