### ISSUE TITLE
Int8/Uint8 convolution support

### ISSUE THREAD

**Issue by christ115** [ermig1979/Simd#79]
Just for your information.

In the near two years, model quantization is becoming popular in deep learning, especially for mobile devices. The core of quantization is low-bits (usually in 8-bits) convolution, which can reduce the memory bandwidth and run-time of deep network significantly.  Many deep learning frameworks have implemented related features, e.g.,
- tensorflow: https://arxiv.org/abs/1712.05877
- pytorch: https://code.fb.com/ml-applications/qnnpack/
- ...

Do you have plan to add this feature into SimdLib?

**Comment by ermig1979** [comment]
Recently I spend main time to optimize the inference of neural network on the base of 
[Synet](https://github.com/ermig1979/Synet) and [Simd Library](https://github.com/ermig1979/Simd). Of course I know about model quantization and have corresponding plans. But these are medium term plans. In the nearest future I'm going to add support of NHWC data format (native data format for Tensorflow) to Synet and optimizations for ARM NEON.
