### ISSUE TITLE
YUV buffer load/resize example

### ISSUE THREAD

**Issue by thefastman** [ermig1979/Simd#81]
Hi ! Can you please provide simple example how I can use Simd to load/use YUV buffer and resize it.
Thanks.

**Comment by ermig1979** [comment]
This a simple example:

    // Input image 1920x1080 in YUV420p format.
    View srcY(1920, 1080, View::Gray8);
    View srcU(960, 540, View::Gray8);
    View srcV(960, 540, View::Gray8);

    // Output image 1280x720 in YUV420p format.
    View dstY(1280, 720, View::Gray8);
    View dstU(640, 360, View::Gray8);
    View dstV(640, 360, View::Gray8);

    Simd::ResizeBilinear(srcY, dstY);
    Simd::ResizeBilinear(srcU, dstU);
    Simd::ResizeBilinear(srcV, dstV);

In order to resize YUV you have to resize of each its planes.

**Comment by thefastman** [comment]
Thanks !
