### ISSUE TITLE
Test.exe crashes

### ISSUE THREAD

**Issue by mikeversteeg** [ermig1979/Simd#82]
I'm looking forward trying SIMD library for video conversions, so installed simd.4.2.73.zip, VS2017, Windows SDK 8.1, loaded the vs2017w project file, selected x64 & release and hit Build. This ran successfully, be it rather slow (never used VS so have no reference) and it looks like all files are made. I have not actually used the dll but did try Test.exe and notice it crashes after the 4th line. I also tried running "Test -m=a -tt=1 -f=Sobel -ot=log.txt" which gives me an error that Sobel is not found, and without that filter it also crashes after a few lines. I'm now left wondering if I made an error building the library. Windows 7/64.
![untitled](https://user-images.githubusercontent.com/46790724/51335046-617a0200-1a81-11e9-863d-e416e7912a63.png)

**Comment by ermig1979** [comment]
Hello.
I got simd.4.2.73 release. Built it with using of Visual Studio 2017 and ran. All tests were finished successful. But it probably I have another OS (Win 10) and CPU.
Could you give me more information about you CPU?

**Comment by mikeversteeg** [comment]
Intel i7-860. I realise it doesn't do avx but assume you test for that?

**Comment by ermig1979** [comment]
The library checks availability of AVX at runtime. So it must work at all x86_64 CPU. 
May be it has some errors, but I can't check it. 
I recommend to uncomment macros SIMD_AVX_DISABLE,  SIMD_AVX2_DISABLE, SIMD_AVX512F_DISABLE and SIMD_AVX512BW_DISABLE in file SimdConfig.h.

**Comment by mikeversteeg** [comment]
Thanks, but I want avx support on machines that do support it. Anything I can do to help you find the bug?

**Comment by ermig1979** [comment]
I hope that error at tests.  I changed some test project options (besides other changes). Yoг can try to update current version at github.

**Comment by mikeversteeg** [comment]
![untitled](https://user-images.githubusercontent.com/46790724/51380878-fed14680-1b12-11e9-870d-97eeab57d503.png)

**Comment by mikeversteeg** [comment]
FYI: tested on another PC (W10, i7-6900K) and there Test works fine, so my build seems OK.

**Comment by mikeversteeg** [comment]
I was already impressed with the cleanness of this library and its documentation, but I can now also add my admiration for its performance. Fabulous! Note your library is also compatible with (at least the latest version of) C++ Builder, so I kindly suggest to change the following two lines in SimdLib.h from

#if defined (_MSC_VER)
#if defined(__GNUC__) || (defined(_MSC_VER) && (_MSC_VER >= 1600))

to

#if defined (_MSC_VER) || (__CODEGEARC__)
#if defined(__GNUC__) || (defined(_MSC_VER) && (_MSC_VER >= 1600)) || 
  (defined(__CODEGEARC__) && (__CODEGEARC__ >= 1840))

As I have many users with various kind of CPU's I do hope you can fix the CPU detection, if not I will not be able to use this library. Let me know how I can help.

**Comment by ermig1979** [comment]
I have added the macros. Could you check?

**Comment by mikeversteeg** [comment]
Sure. But do you plan to look into the cpu detection issue?

**Comment by mikeversteeg** [comment]
BTW: any plans to add YUVA support? Right now you seem to be throwing away the alpha in RGBA..

**Comment by ermig1979** [comment]
YUVA? What is this?

**Comment by mikeversteeg** [comment]
YUVAxxxp is planar YUV with an additional 8-bit alpha plane. Currently your RGBA functions don't work properly as they do not preserve alpha.

**Comment by ermig1979** [comment]
Could you give me a link to description of this image format?

**Comment by mikeversteeg** [comment]
FFmpeg introduced it some 10 years ago. It's an additional uncompressed 8 bit plane following a standard YUV plane. I cannot find any official documentation (no surprise there) but if you doubt its existence just Google yuva420p. I'm just converting back and forth so don't really care if you use the FFmpeg, Gstreamer or VP8 implementation, but FFmpeg 's seems best established and quite intuitive. Alternatively I'm fine with a separate alpha array as well and I'll just add it to the YUV frame. Now I first need to strip alpha from RGBA, and later insert it. That's extra memory access.

**Comment by ermig1979** [comment]
I.e the function will be something like this:

        void Yuva420pToBgra(const uint8_t * y, size_t yStride, const uint8_t * u, size_t uStride, const uint8_t * v, size_t vStride, const uint8_t * a, size_t aStride,
            size_t width, size_t height, uint8_t * bgra, size_t bgraStride);

I will try to add it when I have free time.

**Comment by mikeversteeg** [comment]
Thank you! Note I will also need BgraToYuva420p(). I use x64 exclusively, and can test for you on various CPUs. 
As for the issue with the i7-860, I'm currently learning how to debug a dll in VS, maybe that will give you some more insight.

**Comment by ermig1979** [comment]
F5

**Comment by mikeversteeg** [comment]
Does this help?
![untitled](https://user-images.githubusercontent.com/46790724/51466871-7a2d3500-1d6b-11e9-875c-0d01b9de0f49.png)

**Comment by mikeversteeg** [comment]
I also made a Release build, which crashes like previous master.
![untitled](https://user-images.githubusercontent.com/46790724/51478307-65609980-1d8b-11e9-9bf8-8cb416211a24.png)

**Comment by ermig1979** [comment]
I have added Yuva420pToBgra.

**Comment by mikeversteeg** [comment]
Already? Wow, thank you! I'll go test it today.

**Comment by mikeversteeg** [comment]
Ah, I cannot test yet as I need BgraToYuva420p() first (see above, it's a back and forth encode/decode).

**Comment by mikeversteeg** [comment]
Regarding the bug with the i7-860 I suggest we consider this a fluke, maybe it is a fault in the CPU. So I suggest we close this. When/if you have added BgraToYuva420p (see issue #84) I will release my code as beta which means it will be tested by hundreds of people. If there's really a bug in your code I am sure  it will come to light, in which case I will reopen this.
Meanwhile if there's anything you'd like me to test then just ask.

**Comment by ermig1979** [comment]
ОК.
