### ISSUE TITLE
Interleaved YUV (UYVY)

### ISSUE THREAD

**Issue by mikeversteeg** [ermig1979/Simd#83]
Any plans to add support for converting interleaved YUV to BGR?

**Comment by mikeversteeg** [comment]
No, uyvy422 and uyvy420. Just want to know if you've any plans to grow your library with these video camera formats.

**Comment by mikeversteeg** [comment]
CNN, as in the TV station? 

I know enough about this that I can appreciate the work involved. Unfortunately I already have more coding work than I can manage, which is why I'm so happy I found your library :). However, if it helps, I can make small donations for the extra work. And of course I will thoroughly test the functions I use.

**Comment by ermig1979** [comment]
The second of course (CNN - convolutional neural network).

**Comment by w136111526** [comment]
I also need a yuv video format conversion, for example from nv12 to yuv420，and so on

**Comment by ermig1979** [comment]
> I also need a yuv video format conversion like opencv, for example from nv12 to yuv420，and so on

I could use Simd::Frame.

**Comment by mikeversteeg** [comment]
AFAIK you have not added this, right? Sometimes I get lost in the documentation..

Using existing functionality, is there any way to efficiently convert UYVY (422 interleaved) to YUV422P (or directly to YUV420P)?

This is UYVY: https://docs.microsoft.com/en-us/windows/win32/medfound/recommended-8-bit-yuv-formats-for-video-rendering#uyvy

**Comment by ermig1979** [comment]
Time goes so fast. It seems yesterday I postponed this task for a couple weeks and already more than two years had passed.

I think  that conversion (UYVY  to YUV422P) may be emulated with double using of SimdDeinterleaveUv.

**Comment by mikeversteeg** [comment]
Almost 3 actually :)
I already looked into SimdDeinterleaveUv but did not see how to extract Y. I guess that's what you use the second run for, and use a dummy for the second plane? Mmm..

**Comment by ermig1979** [comment]
u0y0v0y1 -> u0v0 and y0y1 ; u0v0 -> u0 and v0.

**Comment by mikeversteeg** [comment]
Ah, thank you! And please do let me know when this can be done in one call as per my original request.

**Comment by mikeversteeg** [comment]
Do I need to manually copy each line of the V bitmap to convert to 420, or do you see a trick to do this without further loss?

**Comment by mikeversteeg** [comment]
It's working but there's definitely a performance hit, not only because there is additional memory access, but also because I'm deinterlacing to 422 first before I deinterlace again to 420. I hope you will add a more efficient (single) function. BTW: I will also be working with UYVY+A but obviously the planar A field is not such a big problem when converting to YUVA420p.

**Comment by mikeversteeg** [comment]
Thanks for adding SimdUyvyToBgr() (and more optimisations!). Just a friendly reminder that in recent posts (2021) in this thread I've also requested for UYVY422 to YUV420P support. As discussed this is currently done by calling SimdDeinterleaveUv but with a performance hit so I hope there is room for improvement. See also previous post (https://github.com/ermig1979/Simd/issues/83#issuecomment-971921476).

**Comment by ermig1979** [comment]
I need to confirm details of UYVY422 to YUV420P conversion you need:

UYVY422:

    u00 y00 v00 y01
    u10 y10 v10 y11

YUV420P:

    y00 y01
    y10 y11

    (u00 + u10) / 2

    (v00 + v10) / 2

**Comment by mikeversteeg** [comment]
YUV420P and YUVA4224P we've already discussed, and you support these in many functions.

UYVY is a common format in the broadcast world.

UYVY422 is a buffer in the “UYVY” FourCC and represents a 4:2:2 image in YUV colour space. There is a Y sample at every pixel, and U and V sampled at every second pixel horizontally on each line. A macro-pixel contains 2
pixels in 1 DWORD. The ordering of these pixels is U0, Y0, V0, Y1.

UYVA4224 is a buffer that represents a 4:2:2:4 image in YUV colour space. There is a Y sample at every pixels with U and V sampled at every second pixel horizontally. There are two planes in memory, the first being the UYVY
colour plane, and the second the alpha plane that immediately follows the first.

**Comment by ermig1979** [comment]
I added Uyvy422ToBgr function (scalar, SSE4.1, AVX2).

**Comment by mikeversteeg** [comment]
I assumed you meant Uyvy422ToYuv420p so downloaded and compiled today's master but it's not there. I'll wait patiently :)

**Comment by ermig1979** [comment]
I added scalar implementation, SSE4.1 optimizations of function Uyvy422ToYuv420p.

**Comment by mikeversteeg** [comment]
Very nice, thank you!
