### ISSUE TITLE
Plan for NHWC optimization for NEON

### ISSUE THREAD

**Issue by biaoxiaoduan** [ermig1979/Simd#86]
I noticed the NHWC implementation of convolution, and it's extremely fast on AVX2.
But it seems Neon version is not implemented, I didn't find source file named SimdNeonConvolution.cpp.
Do you have any plan for that?

**Comment by ermig1979** [comment]
Yes. I have such plans. Now I'm waiting for ARM dev board (it is arriving 1-2 weeks) to start NEON optimizations.

**Comment by biaoxiaoduan** [comment]
That's great! I am looking foward to that.
