### ISSUE TITLE
Does it support multi-core processing?

### ISSUE THREAD

**Issue by zanazakaryaie** [ermig1979/Simd#88]
Hi

Does this library support multi-core processing by default? If yes, how can I disable it? I want to run it on a single core. Is there any flag like OpenCV's setNumThreads(1)? Or do I have to set some flag in cmake?

**Comment by ermig1979** [comment]
Hi

By default Simd uses only one thread. Number of thread is changed by function SimdSetThreadNumber. 

P.S. Simd::Detection use multithreading by default (last iparameter of function Detection::Init).

**Comment by zanazakaryaie** [comment]
Thanks for your support 👍
