### ISSUE TITLE
signed/unsigned mismatch in SimdLog.h warning

### ISSUE THREAD

**Issue by NickViz** [ermig1979/Simd#90]
Hello Ihar,

when I compile simd-4.3.75 in VS2015, using prj\vs2015\simd.sln I'm getting warning:
simd-4.3.75\src\Simd/SimdLog.h(49): warning C4018: '<': signed/unsigned mismatch (compiling source file ..\..\src\Simd\...

The reason - in SimdLog.h line 39 & 49:
..., size_t size, const...
for (int i = 0; i < size; i++)

Obviously type should be size_t instead of int:
for (size_t i = 0; i < size; i++)

Please fix when you have time.
Nikolai

**Comment by ermig1979** [comment]
The warnings where fixed.
