### ISSUE TITLE
error C2632: 'bool' followed by 'char' is illegal in SimdSse2Statistic.cpp(86)

### ISSUE THREAD

**Issue by NickViz** [ermig1979/Simd#91]
Hello Ihar,

when I compile simd-4.3.75 in VS2015, using prj\vs2015\simd.sln I'm getting error:
..\..\src\Simd\SimdSse2Statistic.cpp(86): error C2632: 'bool' followed by 'char' is illegal

In SimdSse2Statistic.cpp I see the following in lines 86 and 109:
  template <bool small> void GetMoments16(__m128i row, __m128i col,
  template <bool small> SIMD_INLINE void GetMoments8(__m128i mask, __m128i & row, __m128i & col,

The 'small' is defined as byte somewhere else and that makes the compiler error.

As I see the template should be declared as this: 
  template <bool align> void GetMoments16(__m128i row, __m128i col,
  template <bool align> SIMD_INLINE void GetMoments8(__m128i mask, __m128i & row, __m128i & col,

Please fix when you have time.
Nikolai

**Comment by ermig1979** [comment]
This bug has been fixed already. You could wait next release or use current version from github.
