### ISSUE TITLE
Out of range access in Simd::Base::Detect

### ISSUE THREAD

**Issue by ilue** [ermig1979/Simd#93]
Simd::Avx2::Detect may call Simd::Base::Detect with out-of-range startStage.

https://github.com/ermig1979/Simd/blob/2847c808d328704dfb82a8d2318cccf6a5fb2bf1/src/Simd/SimdAvx2Detection.cpp#L424
when i_stage is hid.stages.size() - 1

https://github.com/ermig1979/Simd/blob/2847c808d328704dfb82a8d2318cccf6a5fb2bf1/src/Simd/SimdAvx2Detection.cpp#L449
i_stage + 1 will be hid.stages.size()

https://github.com/ermig1979/Simd/blob/2847c808d328704dfb82a8d2318cccf6a5fb2bf1/src/Simd/SimdDetection.h#L327
so access to stages[startStage] is out-of-range

Similar problem exists in SimdSse41Detection.cpp, SimdNeonDetection.cpp and SimdAvx512bwDetection.cpp.

**Comment by ermig1979** [comment]
Oh! This bug is similar to previous. Thank you!
