### ISSUE TITLE
Found an issue on KernelHwcDefaultBody8

### ISSUE THREAD

**Issue by LDA169** [ermig1979/Simd#94]
Hi rmig1979.
I'm planning to use your library in a private cv project, I found it very interesting.
I found this small issue in the code, fixed in my fork:

in the KernelHwcDefaultBody8 function:
if (dc < dstC)
            {
                __mmask16 tail = TailMask16(dstC - dstCF1);
                __m512 sums[6][1];

the sums variable should be declared as sums[8][1].

Thanks for sharing your work!

**Comment by ermig1979** [comment]
Thank you for bug report. The bug was fixed.
