### ISSUE TITLE
Example of using libsimd convolution

### ISSUE THREAD

**Issue by Mikhail2017** [ermig1979/Simd#95]
Hi all. I'm trying to reproduce results of cv::filter2D using SimdConvolutionForward. Unfortunately I've always got SIGFPE.

Code sample:
`
cv::Mat kernel(3, 3, CV_32FC1, 1. / 9);

void *convolution = ::SimdConvolutionInit(SimdTrue, 1024, 1, fImg.size().height, fImg.size().width, 1, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, SimdConvolutionActivationIdentity, NULL);

cv::Mat filteredfImg(fImg.size(), fImg.type());

::SimdConvolutionSetParams(convolution, kernel.ptr<float>(0, 0), SimdBool::SimdTrue, NULL, NULL, NULL);

::SimdConvolutionForward(convolution, fImg.ptr<float>(0, 0), NULL, filteredfImg.ptr<float>(0, 0));

::SimdRelease(convolution);
`
I've tried different combinations of init parameters.

**Comment by ermig1979** [comment]
Hi, Mikhail!

I would change:

    void *convolution = ::SimdConvolutionInit(SimdFalse, 1, 1, fImg.size().height, fImg.size().width, 1, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, SimdConvolutionActivationIdentity, NULL);
    cv::Mat filteredfImg(fImg.size(), fImg.type());
    ::SimdConvolutionSetParams(convolution, kernel.ptr(0, 0), SimdFalse, NULL, NULL, NULL);
    ::SimdConvolutionForward(convolution, fImg.ptr(0, 0), NULL, filteredfImg.ptr(0, 0));
    ::SimdRelease(convolution);

Also I want to note, that this framework is not effective for such using. It is designed  for inference of neural network.

**Comment by Mikhail2017** [comment]
Thanks, it works. And It's also slower than opencv function, as you have predicted before.
