### ISSUE TITLE
NDK armeabi-v7a build error

### ISSUE THREAD

**Issue by biaoxiaoduan** [ermig1979/Simd#98]
I used script below to build armeabi-v7a
`
cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=ON -DANDROID_PLATFORM=android-21 .
`
And I got error below

`clang++: error: no such file or directory: '7-a'
clang++: error: no such file or directory: '7-a'
make[2]: *** [CMakeFiles/Simd.dir/home/yanbiao/Develop/third_party/Simd/src/Simd/SimdLib.cpp.o] Error 1
make[1]: *** [CMakeFiles/Simd.dir/all] Error 2
`

I tried gcc compiler and got the same error.
Is it the problem of script or build tools? Thanks!

**Comment by ermig1979** [comment]
In order to use cross platform toolchain to build Simd you have to define `TOOLCHAIN` (path to you toolchain) and `TARGET` (i686,  x86_64, ppc, ppc64, arm, aarch64) variables.
