### ISSUE TITLE
Fast Normalized Cross-Correlation using Neon

### ISSUE THREAD

**Issue by sheiling** [ermig1979/Simd#99]
Dear ermig1979,when I using the project "Simd" to speed up my program,have a problem of the ncc formula!
![948709-20170813150021351-1074461639](https://user-images.githubusercontent.com/15042542/59317812-2493fd80-8cf7-11e9-976d-238a2f59976b.png)

I running it on Qualcomm 625 platforms using 8s times. The run time is huge, could you help me to speed up the formula?
thanks for help !

**Comment by ermig1979** [comment]
Hello.

There are many methods to speed up algorithms performance. Usually algorithmic methods give better gain than low level optimizations. I would recommend to try to use integral sum image in your case.

Ihar.

**Comment by sheiling** [comment]
Thanks! 
The advise is good, I will using google for some demo!

**Comment by sheiling** [comment]
Hi ermig1979, I read some code of fast normalized cross correlation, but don't find  any efficient code ! And feel herribly about my project, could you will help me!

**Comment by ermig1979** [comment]
Could you create a project on github with samples of code which you found (or share it any other way)?

**Comment by sheiling** [comment]
en,! This is my lists of the samples code of fast ncc:
1. https://github.com/openmv/openmv/blob/master/src/omv/img/template.c  
2. https://github.com/ukoethe/vigra/blob/master/include/vigra/correlation.hxx 
3. https://www.mathworks.com/matlabcentral/fileexchange/24925-fast-robust-template-matching
the three list codes what I find!  Thanks !!!

**Comment by ermig1979** [comment]
I will watch them in July after holiday. Excuse me for delay.

**Comment by sheiling** [comment]
Just happy for free time , I will wait! 
Thanks!

**Comment by sheiling** [comment]
Dear ermig1979,  could you send email cite to me in private way, I'm sorry trouble you again! Have a good time!

**Comment by sheiling** [comment]
Hello, The July is coming!
